language: r
pandoc_version: 2.0.6
sudo: false
cache:
  packages: yes
  directories:
    - $HOME/bin
    - $TRAVIS_BUILD_DIR/_bookdown_files
    
before_script:
  - chmod +x ./Labs/_build.sh
  - chmod +x ./Labs/_deploy.sh

script:
  - ./Labs/_build.sh
  - ./Labs/_deploy.sh
