<!DOCTYPE html>
<html >

<head>

  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title>Estadística Avanzada para Ciencias Naturales</title>
  <meta name="description" content="Un libro con la teoría, ejemplos y práctica de Estadística Avanzada para Ciencias Naturales.">
  <meta name="generator" content="bookdown 0.7.12 and GitBook 2.6.7">

  <meta property="og:title" content="Estadística Avanzada para Ciencias Naturales" />
  <meta property="og:type" content="book" />
  
  
  <meta property="og:description" content="Un libro con la teoría, ejemplos y práctica de Estadística Avanzada para Ciencias Naturales." />
  

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Estadística Avanzada para Ciencias Naturales" />
  
  <meta name="twitter:description" content="Un libro con la teoría, ejemplos y práctica de Estadística Avanzada para Ciencias Naturales." />
  

<meta name="author" content="Dr. Luciano Selzer">


<meta name="date" content="2018-06-12">

  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-status-bar-style" content="black">
  
  
<link rel="prev" href="regresion.html">
<link rel="next" href="ordenacion-en-espacios-reducidos.html">
<script src="libs/jquery-2.2.3/jquery.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />









<style type="text/css">
a.sourceLine { display: inline-block; line-height: 1.25; }
a.sourceLine { pointer-events: none; color: inherit; text-decoration: inherit; }
a.sourceLine:empty { height: 1.2em; position: absolute; }
.sourceCode { overflow: visible; }
code.sourceCode { white-space: pre; position: relative; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
code.sourceCode { white-space: pre-wrap; }
a.sourceLine { text-indent: -1em; padding-left: 1em; }
}
pre.numberSource a.sourceLine
  { position: relative; }
pre.numberSource a.sourceLine:empty
  { position: absolute; }
pre.numberSource a.sourceLine::before
  { content: attr(data-line-number);
    position: absolute; left: -5em; text-align: right; vertical-align: baseline;
    border: none; pointer-events: all;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {  }
@media screen {
a.sourceLine::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">Laboratorios de Estadística Avanzada</a></li>

<li class="divider"></li>
<li class="chapter" data-level="1" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i><b>1</b> Reglamento</a><ul>
<li class="chapter" data-level="1.1" data-path="index.html"><a href="index.html#asistencia-a-clases-participacion-y-evaluacion-de-pares"><i class="fa fa-check"></i><b>1.1</b> Asistencia a clases, participación y evaluación de pares</a></li>
<li class="chapter" data-level="1.2" data-path="index.html"><a href="index.html#entrega-de-ejercicios"><i class="fa fa-check"></i><b>1.2</b> Entrega de Ejercicios</a></li>
<li class="chapter" data-level="1.3" data-path="index.html"><a href="index.html#laboratorios"><i class="fa fa-check"></i><b>1.3</b> Laboratorios</a></li>
<li class="chapter" data-level="1.4" data-path="index.html"><a href="index.html#cuestionario-de-comprension"><i class="fa fa-check"></i><b>1.4</b> Cuestionario de Comprensión</a></li>
<li class="chapter" data-level="1.5" data-path="index.html"><a href="index.html#parciales"><i class="fa fa-check"></i><b>1.5</b> Parciales</a></li>
<li class="chapter" data-level="1.6" data-path="index.html"><a href="index.html#cronograma"><i class="fa fa-check"></i><b>1.6</b> Cronograma</a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="introduccion-a-r-y-rstudio.html"><a href="introduccion-a-r-y-rstudio.html"><i class="fa fa-check"></i><b>2</b> Introducción a <em>R</em> y RStudio</a><ul>
<li class="chapter" data-level="2.1" data-path="introduccion-a-r-y-rstudio.html"><a href="introduccion-a-r-y-rstudio.html#rstudio"><i class="fa fa-check"></i><b>2.1</b> RStudio</a></li>
<li class="chapter" data-level="2.2" data-path="introduccion-a-r-y-rstudio.html"><a href="introduccion-a-r-y-rstudio.html#analisis-reproducible"><i class="fa fa-check"></i><b>2.2</b> Análisis Reproducible</a><ul>
<li class="chapter" data-level="2.2.1" data-path="introduccion-a-r-y-rstudio.html"><a href="introduccion-a-r-y-rstudio.html#rmarkdown"><i class="fa fa-check"></i><b>2.2.1</b> Rmarkdown</a></li>
</ul></li>
<li class="chapter" data-level="2.3" data-path="introduccion-a-r-y-rstudio.html"><a href="introduccion-a-r-y-rstudio.html#integrando-codigo"><i class="fa fa-check"></i><b>2.3</b> Integrando código</a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="visualizacion-de-datos.html"><a href="visualizacion-de-datos.html"><i class="fa fa-check"></i><b>3</b> Visualización de Datos</a><ul>
<li class="chapter" data-level="3.1" data-path="visualizacion-de-datos.html"><a href="visualizacion-de-datos.html#introduccion"><i class="fa fa-check"></i><b>3.1</b> Introducción</a></li>
<li class="chapter" data-level="3.2" data-path="visualizacion-de-datos.html"><a href="visualizacion-de-datos.html#el-conjunto-de-datos-mpg"><i class="fa fa-check"></i><b>3.2</b> El conjunto de datos <code>mpg</code></a></li>
<li class="chapter" data-level="3.3" data-path="visualizacion-de-datos.html"><a href="visualizacion-de-datos.html#graficos-con-ggplot"><i class="fa fa-check"></i><b>3.3</b> Gráficos con ggplot</a></li>
<li class="chapter" data-level="3.4" data-path="visualizacion-de-datos.html"><a href="visualizacion-de-datos.html#mapeando"><i class="fa fa-check"></i><b>3.4</b> Mapeando</a></li>
<li class="chapter" data-level="3.5" data-path="visualizacion-de-datos.html"><a href="visualizacion-de-datos.html#formas-geometricas"><i class="fa fa-check"></i><b>3.5</b> Formas geometricas</a></li>
<li class="chapter" data-level="3.6" data-path="visualizacion-de-datos.html"><a href="visualizacion-de-datos.html#transformaciones-estadisticas"><i class="fa fa-check"></i><b>3.6</b> Transformaciones Estadísticas</a></li>
<li class="chapter" data-level="3.7" data-path="visualizacion-de-datos.html"><a href="visualizacion-de-datos.html#ajuste-de-posiciones"><i class="fa fa-check"></i><b>3.7</b> Ajuste de Posiciones</a></li>
<li class="chapter" data-level="3.8" data-path="visualizacion-de-datos.html"><a href="visualizacion-de-datos.html#sistemas-de-coordenadas"><i class="fa fa-check"></i><b>3.8</b> Sistemas de Coordenadas</a></li>
<li class="chapter" data-level="3.9" data-path="visualizacion-de-datos.html"><a href="visualizacion-de-datos.html#personalizando-el-grafico"><i class="fa fa-check"></i><b>3.9</b> Personalizando el gráfico</a></li>
</ul></li>
<li class="chapter" data-level="4" data-path="manejo-de-datos.html"><a href="manejo-de-datos.html"><i class="fa fa-check"></i><b>4</b> Manejo de datos</a><ul>
<li class="chapter" data-level="4.1" data-path="manejo-de-datos.html"><a href="manejo-de-datos.html#seleccionando-datos"><i class="fa fa-check"></i><b>4.1</b> Seleccionando datos</a></li>
<li class="chapter" data-level="4.2" data-path="manejo-de-datos.html"><a href="manejo-de-datos.html#seleccionando-columnas"><i class="fa fa-check"></i><b>4.2</b> Seleccionando columnas</a></li>
<li class="chapter" data-level="4.3" data-path="manejo-de-datos.html"><a href="manejo-de-datos.html#agregando-columnas"><i class="fa fa-check"></i><b>4.3</b> Agregando columnas</a></li>
<li class="chapter" data-level="4.4" data-path="manejo-de-datos.html"><a href="manejo-de-datos.html#operaciones-por-grupos"><i class="fa fa-check"></i><b>4.4</b> Operaciones por grupos</a></li>
<li class="chapter" data-level="4.5" data-path="manejo-de-datos.html"><a href="manejo-de-datos.html#formato-ancho-y-formato-largo"><i class="fa fa-check"></i><b>4.5</b> Formato Ancho y Formato Largo</a></li>
<li class="chapter" data-level="4.6" data-path="manejo-de-datos.html"><a href="manejo-de-datos.html#por-su-cuenta"><i class="fa fa-check"></i><b>4.6</b> Por su cuenta</a></li>
</ul></li>
<li class="chapter" data-level="5" data-path="anova.html"><a href="anova.html"><i class="fa fa-check"></i><b>5</b> ANOVA</a><ul>
<li class="chapter" data-level="5.1" data-path="anova.html"><a href="anova.html#algunos-conceptos-importantes"><i class="fa fa-check"></i><b>5.1</b> Algunos conceptos importantes</a></li>
<li class="chapter" data-level="5.2" data-path="anova.html"><a href="anova.html#diseno-de-estudios-de-anova"><i class="fa fa-check"></i><b>5.2</b> Diseño de Estudios de ANOVA</a></li>
<li class="chapter" data-level="5.3" data-path="anova.html"><a href="anova.html#planificacion-de-experimentos"><i class="fa fa-check"></i><b>5.3</b> Planificación De Experimentos</a></li>
<li class="chapter" data-level="5.4" data-path="anova.html"><a href="anova.html#usos-del-anova"><i class="fa fa-check"></i><b>5.4</b> Usos Del ANOVA</a></li>
<li class="chapter" data-level="5.5" data-path="anova.html"><a href="anova.html#modelo-i-de-anova.-niveles-del-factor-fijos"><i class="fa fa-check"></i><b>5.5</b> MODELO I DE ANOVA. NIVELES DEL FACTOR FIJOS</a><ul>
<li class="chapter" data-level="5.5.1" data-path="anova.html"><a href="anova.html#distincion-entre-modelos-i-y-ii-de-anova"><i class="fa fa-check"></i><b>5.5.1</b> Distinción Entre Modelos I Y II de ANOVA</a></li>
<li class="chapter" data-level="5.5.2" data-path="anova.html"><a href="anova.html#ideas-basicas"><i class="fa fa-check"></i><b>5.5.2</b> Ideas Básicas</a></li>
</ul></li>
<li class="chapter" data-level="5.6" data-path="anova.html"><a href="anova.html#comprobacion-de-los-supuestos"><i class="fa fa-check"></i><b>5.6</b> Comprobación de los Supuestos</a><ul>
<li class="chapter" data-level="5.6.1" data-path="anova.html"><a href="anova.html#prueba-para-igualdad-de-varianzas"><i class="fa fa-check"></i><b>5.6.1</b> Prueba para igualdad de varianzas</a></li>
<li class="chapter" data-level="5.6.2" data-path="anova.html"><a href="anova.html#prueba-de-kolmogorov---smirnov-modificacion-de-lilliefors-para-estudiar-normalidad"><i class="fa fa-check"></i><b>5.6.2</b> Prueba de Kolmogorov - Smirnov (modificación de Lilliefors) para estudiar Normalidad</a></li>
<li class="chapter" data-level="5.6.3" data-path="anova.html"><a href="anova.html#residuos"><i class="fa fa-check"></i><b>5.6.3</b> Residuos</a></li>
<li class="chapter" data-level="5.6.4" data-path="anova.html"><a href="anova.html#graficos-de-residuos"><i class="fa fa-check"></i><b>5.6.4</b> Gráficos de Residuos</a></li>
</ul></li>
<li class="chapter" data-level="5.7" data-path="anova.html"><a href="anova.html#transformaciones"><i class="fa fa-check"></i><b>5.7</b> Transformaciones</a><ul>
<li class="chapter" data-level="5.7.1" data-path="anova.html"><a href="anova.html#transformaciones-para-estabilizar-las-varianzas"><i class="fa fa-check"></i><b>5.7.1</b> Transformaciones para estabilizar las Varianzas</a></li>
<li class="chapter" data-level="5.7.2" data-path="anova.html"><a href="anova.html#transformaciones-para-corregir-la-falta-de-normalidad"><i class="fa fa-check"></i><b>5.7.2</b> Transformaciones para corregir la falta de normalidad</a></li>
<li class="chapter" data-level="5.7.3" data-path="anova.html"><a href="anova.html#efectos-del-alejamiento-de-los-supuestos-del-modelo"><i class="fa fa-check"></i><b>5.7.3</b> Efectos Del Alejamiento De Los Supuestos Del Modelo</a></li>
</ul></li>
<li class="chapter" data-level="5.8" data-path="anova.html"><a href="anova.html#formulacion-del-modelo-i-de-anova."><i class="fa fa-check"></i><b>5.8</b> Formulación Del Modelo I De ANOVA.</a><ul>
<li class="chapter" data-level="5.8.1" data-path="anova.html"><a href="anova.html#caracteristicas-importantes-del-modelo"><i class="fa fa-check"></i><b>5.8.1</b> Características importantes del modelo</a></li>
<li class="chapter" data-level="5.8.2" data-path="anova.html"><a href="anova.html#interpretacion-de-las-medias-de-los-niveles-del-factor"><i class="fa fa-check"></i><b>5.8.2</b> Interpretación De Las Medias De Los Niveles Del Factor</a></li>
<li class="chapter" data-level="5.8.3" data-path="anova.html"><a href="anova.html#ajustando-el-modelo"><i class="fa fa-check"></i><b>5.8.3</b> Ajustando El Modelo</a></li>
<li class="chapter" data-level="5.8.4" data-path="anova.html"><a href="anova.html#estimadores-de-minimos-cuadrados"><i class="fa fa-check"></i><b>5.8.4</b> Estimadores De Mínimos Cuadrados</a></li>
</ul></li>
<li class="chapter" data-level="5.9" data-path="anova.html"><a href="anova.html#particion-de-la-suma-de-cuadrados-total"><i class="fa fa-check"></i><b>5.9</b> Partición De La Suma De Cuadrados Total</a><ul>
<li class="chapter" data-level="5.9.1" data-path="anova.html"><a href="anova.html#formulas-computatorias"><i class="fa fa-check"></i><b>5.9.1</b> Fórmulas computatorias</a></li>
</ul></li>
<li class="chapter" data-level="5.10" data-path="anova.html"><a href="anova.html#grados-de-libertad"><i class="fa fa-check"></i><b>5.10</b> Grados De Libertad</a></li>
<li class="chapter" data-level="5.11" data-path="anova.html"><a href="anova.html#cuadrados-medios"><i class="fa fa-check"></i><b>5.11</b> Cuadrados Medios</a><ul>
<li class="chapter" data-level="5.11.1" data-path="anova.html"><a href="anova.html#esperanza-de-los-cuadrados-medios"><i class="fa fa-check"></i><b>5.11.1</b> Esperanza de los Cuadrados Medios</a></li>
<li class="chapter" data-level="5.11.2" data-path="anova.html"><a href="anova.html#comentarios-1"><i class="fa fa-check"></i><b>5.11.2</b> Comentarios</a></li>
</ul></li>
<li class="chapter" data-level="5.12" data-path="anova.html"><a href="anova.html#prueba-f-para-la-igualdad-de-las-medias-de-los-niveles-del-factor"><i class="fa fa-check"></i><b>5.12</b> Prueba F para la Igualdad de las Medias de los Niveles del Factor</a><ul>
<li class="chapter" data-level="5.12.1" data-path="anova.html"><a href="anova.html#prueba-estadistica"><i class="fa fa-check"></i><b>5.12.1</b> Prueba Estadística</a></li>
<li class="chapter" data-level="5.12.2" data-path="anova.html"><a href="anova.html#distribucion-de-mathbffmathbf"><i class="fa fa-check"></i><b>5.12.2</b> Distribución de <span class="math inline">\(\mathbf{F}^{\mathbf{*}}\)</span></a></li>
<li class="chapter" data-level="5.12.3" data-path="anova.html"><a href="anova.html#regla-de-decision"><i class="fa fa-check"></i><b>5.12.3</b> Regla De Decisión</a></li>
<li class="chapter" data-level="5.12.4" data-path="anova.html"><a href="anova.html#comentario"><i class="fa fa-check"></i><b>5.12.4</b> Comentario</a></li>
</ul></li>
<li class="chapter" data-level="5.13" data-path="anova.html"><a href="anova.html#formulacion-alternativa-del-modelo-i"><i class="fa fa-check"></i><b>5.13</b> Formulación Alternativa Del Modelo I</a><ul>
<li class="chapter" data-level="5.13.1" data-path="anova.html"><a href="anova.html#definicion-de-mathbfmu_mathbfbullet"><i class="fa fa-check"></i><b>5.13.1</b> Definición de <span class="math inline">\(\mathbf{\mu}_{\mathbf{\bullet}}\)</span></a></li>
</ul></li>
<li class="chapter" data-level="5.14" data-path="anova.html"><a href="anova.html#prueba-para-la-igualdad-de-las-medias-de-los-niveles-del-factor"><i class="fa fa-check"></i><b>5.14</b> Prueba Para La Igualdad De Las Medias De Los Niveles Del Factor</a></li>
<li class="chapter" data-level="5.15" data-path="anova.html"><a href="anova.html#analisis-de-los-efectos-del-nivel-del-factor"><i class="fa fa-check"></i><b>5.15</b> Análisis De Los Efectos Del Nivel Del Factor</a><ul>
<li class="chapter" data-level="5.15.1" data-path="anova.html"><a href="anova.html#graficos-de-las-estimaciones-de-las-medias-de-los-niveles-del-factor"><i class="fa fa-check"></i><b>5.15.1</b> Gráficos de las estimaciones de las medias de los niveles del factor</a></li>
<li class="chapter" data-level="5.15.2" data-path="anova.html"><a href="anova.html#estimacion-de-los-efectos-de-los-niveles-del-factor"><i class="fa fa-check"></i><b>5.15.2</b> Estimación de los efectos de los niveles del factor</a></li>
<li class="chapter" data-level="5.15.3" data-path="anova.html"><a href="anova.html#comparaciones-multiples"><i class="fa fa-check"></i><b>5.15.3</b> Comparaciones múltiples</a></li>
</ul></li>
<li class="chapter" data-level="5.16" data-path="anova.html"><a href="anova.html#planificacion-del-tamano-muestral"><i class="fa fa-check"></i><b>5.16</b> Planificación Del Tamaño Muestral</a><ul>
<li class="chapter" data-level="5.16.1" data-path="anova.html"><a href="anova.html#potencia-de-la-prueba-f"><i class="fa fa-check"></i><b>5.16.1</b> Potencia De La Prueba F</a></li>
</ul></li>
<li class="chapter" data-level="5.17" data-path="anova.html"><a href="anova.html#modelo-ii-de-anova-niveles-del-factor-aleatorios"><i class="fa fa-check"></i><b>5.17</b> Modelo II De ANOVA: Niveles Del Factor Aleatorios</a><ul>
<li class="chapter" data-level="5.17.1" data-path="anova.html"><a href="anova.html#modelo-aleatorio-de-medias-de-celdas."><i class="fa fa-check"></i><b>5.17.1</b> Modelo Aleatorio de Medias de Celdas.</a></li>
<li class="chapter" data-level="5.17.2" data-path="anova.html"><a href="anova.html#caracteristicas-importantes-del-modelo-1"><i class="fa fa-check"></i><b>5.17.2</b> Características importantes del Modelo</a></li>
<li class="chapter" data-level="5.17.3" data-path="anova.html"><a href="anova.html#cuestiones-de-interes"><i class="fa fa-check"></i><b>5.17.3</b> Cuestiones de Interés</a></li>
<li class="chapter" data-level="5.17.4" data-path="anova.html"><a href="anova.html#prueba-para-mathbfsigma_mathbfmumathbf2-0"><i class="fa fa-check"></i><b>5.17.4</b> Prueba para <span class="math inline">\(\mathbf{\sigma}_{\mathbf{\mu}}^{\mathbf{2}}\)</span> = 0</a></li>
<li class="chapter" data-level="5.17.5" data-path="anova.html"><a href="anova.html#estimacion-de-mathbfmu_mathbfbullet"><i class="fa fa-check"></i><b>5.17.5</b> Estimación De <span class="math inline">\(\mathbf{\mu}_{\mathbf{\bullet}}\)</span></a></li>
<li class="chapter" data-level="5.17.6" data-path="anova.html"><a href="anova.html#estimacion-de-sigma_mu2left-sigma_mu2sigma2-right"><i class="fa fa-check"></i><b>5.17.6</b> Estimación De <span class="math inline">\(\sigma_{\mu}^2/\left ( \sigma_{\mu}^2+\sigma^2 \right )\)</span></a></li>
<li class="chapter" data-level="5.17.7" data-path="anova.html"><a href="anova.html#modelo-de-efectos-aleatorios"><i class="fa fa-check"></i><b>5.17.7</b> Modelo De Efectos Aleatorios</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="6" data-path="problemas-anova-simple.html"><a href="problemas-anova-simple.html"><i class="fa fa-check"></i><b>6</b> Problemas ANOVA Simple</a><ul>
<li class="chapter" data-level="6.0.1" data-path="problemas-anova-simple.html"><a href="problemas-anova-simple.html#recordatorio"><i class="fa fa-check"></i><b>6.0.1</b> Recordatorio</a></li>
<li class="chapter" data-level="6.1" data-path="problemas-anova-simple.html"><a href="problemas-anova-simple.html#problemas"><i class="fa fa-check"></i><b>6.1</b> Problemas</a><ul>
<li class="chapter" data-level="6.1.1" data-path="problemas-anova-simple.html"><a href="problemas-anova-simple.html#contrastes"><i class="fa fa-check"></i><b>6.1.1</b> Contrastes</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="7" data-path="anova-de-dos-factores.html"><a href="anova-de-dos-factores.html"><i class="fa fa-check"></i><b>7</b> ANOVA DE DOS FACTORES</a><ul>
<li class="chapter" data-level="7.1" data-path="anova-de-dos-factores.html"><a href="anova-de-dos-factores.html#ventajas-de-los-estudios-multifactoriales"><i class="fa fa-check"></i><b>7.1</b> Ventajas de los estudios multifactoriales</a><ul>
<li class="chapter" data-level="7.1.1" data-path="anova-de-dos-factores.html"><a href="anova-de-dos-factores.html#eficiencia"><i class="fa fa-check"></i><b>7.1.1</b> Eficiencia:</a></li>
</ul></li>
<li class="chapter" data-level="7.2" data-path="anova-de-dos-factores.html"><a href="anova-de-dos-factores.html#elementos-del-modelo"><i class="fa fa-check"></i><b>7.2</b> Elementos del Modelo</a><ul>
<li class="chapter" data-level="7.2.1" data-path="anova-de-dos-factores.html"><a href="anova-de-dos-factores.html#efectos-principales"><i class="fa fa-check"></i><b>7.2.1</b> Efectos principales</a></li>
</ul></li>
<li class="chapter" data-level="7.3" data-path="anova-de-dos-factores.html"><a href="anova-de-dos-factores.html#representacion-grafica"><i class="fa fa-check"></i><b>7.3</b> Representación gráfica</a></li>
<li class="chapter" data-level="7.4" data-path="anova-de-dos-factores.html"><a href="anova-de-dos-factores.html#interaccion"><i class="fa fa-check"></i><b>7.4</b> Interacción</a><ul>
<li class="chapter" data-level="7.4.1" data-path="anova-de-dos-factores.html"><a href="anova-de-dos-factores.html#interacciones-no-importantes"><i class="fa fa-check"></i><b>7.4.1</b> Interacciones no importantes</a></li>
</ul></li>
<li class="chapter" data-level="7.5" data-path="anova-de-dos-factores.html"><a href="anova-de-dos-factores.html#modelo-i-para-estudios-de-dos-factores"><i class="fa fa-check"></i><b>7.5</b> MODELO I PARA ESTUDIOS DE DOS FACTORES</a><ul>
<li class="chapter" data-level="7.5.1" data-path="anova-de-dos-factores.html"><a href="anova-de-dos-factores.html#modelo-de-las-medias-de-celdas"><i class="fa fa-check"></i><b>7.5.1</b> Modelo de las medias de celdas</a></li>
<li class="chapter" data-level="7.5.2" data-path="anova-de-dos-factores.html"><a href="anova-de-dos-factores.html#modelo-de-los-efectos-de-los-factores"><i class="fa fa-check"></i><b>7.5.2</b> Modelo de los efectos de los factores</a></li>
<li class="chapter" data-level="7.5.3" data-path="anova-de-dos-factores.html"><a href="anova-de-dos-factores.html#anova-modelo-i"><i class="fa fa-check"></i><b>7.5.3</b> ANOVA (MODELO I)</a></li>
</ul></li>
<li class="chapter" data-level="7.6" data-path="anova-de-dos-factores.html"><a href="anova-de-dos-factores.html#prueba-de-f"><i class="fa fa-check"></i><b>7.6</b> Prueba de F</a></li>
<li class="chapter" data-level="7.7" data-path="anova-de-dos-factores.html"><a href="anova-de-dos-factores.html#contrastes-1"><i class="fa fa-check"></i><b>7.7</b> Contrastes</a><ul>
<li class="chapter" data-level="7.7.1" data-path="anova-de-dos-factores.html"><a href="anova-de-dos-factores.html#entre-filas"><i class="fa fa-check"></i><b>7.7.1</b> Entre Filas</a></li>
<li class="chapter" data-level="7.7.2" data-path="anova-de-dos-factores.html"><a href="anova-de-dos-factores.html#entre-columnas"><i class="fa fa-check"></i><b>7.7.2</b> Entre columnas</a></li>
<li class="chapter" data-level="7.7.3" data-path="anova-de-dos-factores.html"><a href="anova-de-dos-factores.html#interaccion-1"><i class="fa fa-check"></i><b>7.7.3</b> Interacción</a></li>
</ul></li>
<li class="chapter" data-level="7.8" data-path="anova-de-dos-factores.html"><a href="anova-de-dos-factores.html#potencia-de-la-prueba-f-1"><i class="fa fa-check"></i><b>7.8</b> Potencia de la prueba F</a><ul>
<li class="chapter" data-level="7.8.1" data-path="anova-de-dos-factores.html"><a href="anova-de-dos-factores.html#interaccion-2"><i class="fa fa-check"></i><b>7.8.1</b> Interacción</a></li>
<li class="chapter" data-level="7.8.2" data-path="anova-de-dos-factores.html"><a href="anova-de-dos-factores.html#prueba-para-el-factor-principal-a"><i class="fa fa-check"></i><b>7.8.2</b> Prueba para el factor principal A:</a></li>
<li class="chapter" data-level="7.8.3" data-path="anova-de-dos-factores.html"><a href="anova-de-dos-factores.html#prueba-para-el-factor-principal-b"><i class="fa fa-check"></i><b>7.8.3</b> Prueba para el factor principal B:</a></li>
</ul></li>
<li class="chapter" data-level="7.9" data-path="anova-de-dos-factores.html"><a href="anova-de-dos-factores.html#caso-de-una-observacion-por-tratamiento"><i class="fa fa-check"></i><b>7.9</b> CASO DE UNA OBSERVACIÓN POR TRATAMIENTO</a><ul>
<li class="chapter" data-level="7.9.1" data-path="anova-de-dos-factores.html"><a href="anova-de-dos-factores.html#modelo-sin-interaccion"><i class="fa fa-check"></i><b>7.9.1</b> Modelo sin interacción</a></li>
<li class="chapter" data-level="7.9.2" data-path="anova-de-dos-factores.html"><a href="anova-de-dos-factores.html#prueba-de-tukey-aditividad"><i class="fa fa-check"></i><b>7.9.2</b> Prueba de Tukey (Aditividad)</a></li>
</ul></li>
<li class="chapter" data-level="7.10" data-path="anova-de-dos-factores.html"><a href="anova-de-dos-factores.html#modelo-ii-y-modelo-iii-para-estudios-de-dos-factores"><i class="fa fa-check"></i><b>7.10</b> MODELO II Y MODELO III PARA ESTUDIOS DE DOS FACTORES</a><ul>
<li class="chapter" data-level="7.10.1" data-path="anova-de-dos-factores.html"><a href="anova-de-dos-factores.html#modelo-aleatorio-modelo-ii"><i class="fa fa-check"></i><b>7.10.1</b> Modelo aleatorio (Modelo II)</a></li>
<li class="chapter" data-level="7.10.2" data-path="anova-de-dos-factores.html"><a href="anova-de-dos-factores.html#modelo-mixto-modelo-iii"><i class="fa fa-check"></i><b>7.10.2</b> Modelo Mixto (Modelo III)</a></li>
<li class="chapter" data-level="7.10.3" data-path="anova-de-dos-factores.html"><a href="anova-de-dos-factores.html#pruebas-estadisticas"><i class="fa fa-check"></i><b>7.10.3</b> Pruebas estadísticas</a></li>
<li class="chapter" data-level="7.10.4" data-path="anova-de-dos-factores.html"><a href="anova-de-dos-factores.html#estimacion-de-los-componentes-de-la-varianza"><i class="fa fa-check"></i><b>7.10.4</b> Estimación de los componentes de la varianza</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="8" data-path="problemas-anova-dos-factores.html"><a href="problemas-anova-dos-factores.html"><i class="fa fa-check"></i><b>8</b> Problemas ANOVA Dos Factores</a><ul>
<li class="chapter" data-level="8.1" data-path="problemas-anova-dos-factores.html"><a href="problemas-anova-dos-factores.html#formulas-con-mas-de-una-variable-independiente"><i class="fa fa-check"></i><b>8.1</b> Formulas con más de una variable independiente</a><ul>
<li class="chapter" data-level="8.1.1" data-path="problemas-anova-dos-factores.html"><a href="problemas-anova-dos-factores.html#aditividadtukey"><i class="fa fa-check"></i><b>8.1.1</b> Test de aditividad de Tukey</a></li>
</ul></li>
<li class="chapter" data-level="8.2" data-path="problemas-anova-dos-factores.html"><a href="problemas-anova-dos-factores.html#problemas-1"><i class="fa fa-check"></i><b>8.2</b> Problemas</a></li>
</ul></li>
<li class="chapter" data-level="9" data-path="prueba-de-wilcoxon-mann-whitney-para-dos-pruebas-independientes.html"><a href="prueba-de-wilcoxon-mann-whitney-para-dos-pruebas-independientes.html"><i class="fa fa-check"></i><b>9</b> Prueba de Wilcoxon-Mann-Whitney para dos pruebas independientes</a><ul>
<li class="chapter" data-level="9.1" data-path="prueba-de-wilcoxon-mann-whitney-para-dos-pruebas-independientes.html"><a href="prueba-de-wilcoxon-mann-whitney-para-dos-pruebas-independientes.html#datos"><i class="fa fa-check"></i><b>9.1</b> Datos</a></li>
<li class="chapter" data-level="9.2" data-path="prueba-de-wilcoxon-mann-whitney-para-dos-pruebas-independientes.html"><a href="prueba-de-wilcoxon-mann-whitney-para-dos-pruebas-independientes.html#supuestos"><i class="fa fa-check"></i><b>9.2</b> Supuestos</a></li>
<li class="chapter" data-level="9.3" data-path="prueba-de-wilcoxon-mann-whitney-para-dos-pruebas-independientes.html"><a href="prueba-de-wilcoxon-mann-whitney-para-dos-pruebas-independientes.html#np-algoritmo"><i class="fa fa-check"></i><b>9.3</b> Procedimiento básico</a><ul>
<li class="chapter" data-level="9.3.1" data-path="prueba-de-wilcoxon-mann-whitney-para-dos-pruebas-independientes.html"><a href="prueba-de-wilcoxon-mann-whitney-para-dos-pruebas-independientes.html#ejemplo"><i class="fa fa-check"></i><b>9.3.1</b> Ejemplo</a></li>
</ul></li>
<li class="chapter" data-level="9.4" data-path="prueba-de-wilcoxon-mann-whitney-para-dos-pruebas-independientes.html"><a href="prueba-de-wilcoxon-mann-whitney-para-dos-pruebas-independientes.html#estadisticos"><i class="fa fa-check"></i><b>9.4</b> Estadísticos</a><ul>
<li class="chapter" data-level="9.4.1" data-path="prueba-de-wilcoxon-mann-whitney-para-dos-pruebas-independientes.html"><a href="prueba-de-wilcoxon-mann-whitney-para-dos-pruebas-independientes.html#variante-wilcoxon-w"><i class="fa fa-check"></i><b>9.4.1</b> Variante Wilcoxon (W)</a></li>
<li class="chapter" data-level="9.4.2" data-path="prueba-de-wilcoxon-mann-whitney-para-dos-pruebas-independientes.html"><a href="prueba-de-wilcoxon-mann-whitney-para-dos-pruebas-independientes.html#variante-mann-whitney-u"><i class="fa fa-check"></i><b>9.4.2</b> Variante Mann-Whitney (U)</a></li>
</ul></li>
<li class="chapter" data-level="9.5" data-path="prueba-de-wilcoxon-mann-whitney-para-dos-pruebas-independientes.html"><a href="prueba-de-wilcoxon-mann-whitney-para-dos-pruebas-independientes.html#hipotesis"><i class="fa fa-check"></i><b>9.5</b> Hipótesis</a><ul>
<li class="chapter" data-level="9.5.1" data-path="prueba-de-wilcoxon-mann-whitney-para-dos-pruebas-independientes.html"><a href="prueba-de-wilcoxon-mann-whitney-para-dos-pruebas-independientes.html#prueba-a-dos-colas"><i class="fa fa-check"></i><b>9.5.1</b> Prueba a dos colas</a></li>
<li class="chapter" data-level="9.5.2" data-path="prueba-de-wilcoxon-mann-whitney-para-dos-pruebas-independientes.html"><a href="prueba-de-wilcoxon-mann-whitney-para-dos-pruebas-independientes.html#prueba-de-una-cola-a-la-izquierda"><i class="fa fa-check"></i><b>9.5.2</b> Prueba de una cola a la izquierda</a></li>
<li class="chapter" data-level="9.5.3" data-path="prueba-de-wilcoxon-mann-whitney-para-dos-pruebas-independientes.html"><a href="prueba-de-wilcoxon-mann-whitney-para-dos-pruebas-independientes.html#prueba-de-una-cola-a-la-derecha"><i class="fa fa-check"></i><b>9.5.3</b> Prueba de una cola a la derecha</a></li>
</ul></li>
<li class="chapter" data-level="9.6" data-path="prueba-de-wilcoxon-mann-whitney-para-dos-pruebas-independientes.html"><a href="prueba-de-wilcoxon-mann-whitney-para-dos-pruebas-independientes.html#ejemplo-2"><i class="fa fa-check"></i><b>9.6</b> Ejemplo 2</a></li>
<li class="chapter" data-level="9.7" data-path="prueba-de-wilcoxon-mann-whitney-para-dos-pruebas-independientes.html"><a href="prueba-de-wilcoxon-mann-whitney-para-dos-pruebas-independientes.html#prueba-de-wilcoxon-de-rangos-con-signo-para-muestras-apareadas"><i class="fa fa-check"></i><b>9.7</b> Prueba de Wilcoxon de rangos con signo para muestras apareadas</a><ul>
<li class="chapter" data-level="9.7.1" data-path="prueba-de-wilcoxon-mann-whitney-para-dos-pruebas-independientes.html"><a href="prueba-de-wilcoxon-mann-whitney-para-dos-pruebas-independientes.html#supuestos-1"><i class="fa fa-check"></i><b>9.7.1</b> Supuestos</a></li>
<li class="chapter" data-level="9.7.2" data-path="prueba-de-wilcoxon-mann-whitney-para-dos-pruebas-independientes.html"><a href="prueba-de-wilcoxon-mann-whitney-para-dos-pruebas-independientes.html#estadisticos-1"><i class="fa fa-check"></i><b>9.7.2</b> Estadísticos</a></li>
<li class="chapter" data-level="9.7.3" data-path="prueba-de-wilcoxon-mann-whitney-para-dos-pruebas-independientes.html"><a href="prueba-de-wilcoxon-mann-whitney-para-dos-pruebas-independientes.html#hipotesis-1"><i class="fa fa-check"></i><b>9.7.3</b> Hipótesis</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="10" data-path="ejercicios-de-dos-muestras-no-parametrico.html"><a href="ejercicios-de-dos-muestras-no-parametrico.html"><i class="fa fa-check"></i><b>10</b> Ejercicios de dos muestras no paramétrico</a><ul>
<li class="chapter" data-level="10.1" data-path="ejercicios-de-dos-muestras-no-parametrico.html"><a href="ejercicios-de-dos-muestras-no-parametrico.html#reproduciendo-el-algoritmo-manualmente"><i class="fa fa-check"></i><b>10.1</b> Reproduciendo el algoritmo manualmente</a></li>
<li class="chapter" data-level="10.2" data-path="ejercicios-de-dos-muestras-no-parametrico.html"><a href="ejercicios-de-dos-muestras-no-parametrico.html#funciones-no-parametricas-en-r"><i class="fa fa-check"></i><b>10.2</b> Funciones no paramétricas en <em>R</em></a></li>
<li class="chapter" data-level="10.3" data-path="ejercicios-de-dos-muestras-no-parametrico.html"><a href="ejercicios-de-dos-muestras-no-parametrico.html#formulas"><i class="fa fa-check"></i><b>10.3</b> Fórmulas</a></li>
<li class="chapter" data-level="10.4" data-path="ejercicios-de-dos-muestras-no-parametrico.html"><a href="ejercicios-de-dos-muestras-no-parametrico.html#muestras-apareadas"><i class="fa fa-check"></i><b>10.4</b> Muestras apareadas</a></li>
<li class="chapter" data-level="10.5" data-path="ejercicios-de-dos-muestras-no-parametrico.html"><a href="ejercicios-de-dos-muestras-no-parametrico.html#problemas-2"><i class="fa fa-check"></i><b>10.5</b> Problemas</a></li>
</ul></li>
<li class="chapter" data-level="11" data-path="anova-no-parametrico.html"><a href="anova-no-parametrico.html"><i class="fa fa-check"></i><b>11</b> ANOVA No Paramétrico</a><ul>
<li class="chapter" data-level="11.1" data-path="anova-no-parametrico.html"><a href="anova-no-parametrico.html#pruebas-para-varias-muestras-independientes"><i class="fa fa-check"></i><b>11.1</b> Pruebas para varias muestras independientes</a><ul>
<li class="chapter" data-level="11.1.1" data-path="anova-no-parametrico.html"><a href="anova-no-parametrico.html#prueba-de-la-mediana"><i class="fa fa-check"></i><b>11.1.1</b> Prueba de la mediana</a></li>
</ul></li>
<li class="chapter" data-level="11.2" data-path="anova-no-parametrico.html"><a href="anova-no-parametrico.html#prueba-de-kruskal-wallis"><i class="fa fa-check"></i><b>11.2</b> Prueba de Kruskal-Wallis</a><ul>
<li class="chapter" data-level="11.2.1" data-path="anova-no-parametrico.html"><a href="anova-no-parametrico.html#datos-2"><i class="fa fa-check"></i><b>11.2.1</b> Datos</a></li>
<li class="chapter" data-level="11.2.2" data-path="anova-no-parametrico.html"><a href="anova-no-parametrico.html#supuestos-3"><i class="fa fa-check"></i><b>11.2.2</b> Supuestos</a></li>
<li class="chapter" data-level="11.2.3" data-path="anova-no-parametrico.html"><a href="anova-no-parametrico.html#procedimiento-1"><i class="fa fa-check"></i><b>11.2.3</b> Procedimiento</a></li>
<li class="chapter" data-level="11.2.4" data-path="anova-no-parametrico.html"><a href="anova-no-parametrico.html#hipotesis-3"><i class="fa fa-check"></i><b>11.2.4</b> Hipótesis</a></li>
<li class="chapter" data-level="11.2.5" data-path="anova-no-parametrico.html"><a href="anova-no-parametrico.html#contrastes-3"><i class="fa fa-check"></i><b>11.2.5</b> Contrastes</a></li>
<li class="chapter" data-level="11.2.6" data-path="anova-no-parametrico.html"><a href="anova-no-parametrico.html#comentarios-3"><i class="fa fa-check"></i><b>11.2.6</b> Comentarios</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="12" data-path="problemas-de-anova-no-parametrico.html"><a href="problemas-de-anova-no-parametrico.html"><i class="fa fa-check"></i><b>12</b> Problemas de ANOVA No Paramétrico</a><ul>
<li class="chapter" data-level="12.1" data-path="problemas-de-anova-no-parametrico.html"><a href="problemas-de-anova-no-parametrico.html#problemas-3"><i class="fa fa-check"></i><b>12.1</b> Problemas</a></li>
</ul></li>
<li class="chapter" data-level="13" data-path="disenos-experimentales.html"><a href="disenos-experimentales.html"><i class="fa fa-check"></i><b>13</b> DISEÑOS EXPERIMENTALES</a><ul>
<li class="chapter" data-level="13.1" data-path="disenos-experimentales.html"><a href="disenos-experimentales.html#bloques-al-azar"><i class="fa fa-check"></i><b>13.1</b> Bloques al azar</a><ul>
<li class="chapter" data-level="13.1.1" data-path="disenos-experimentales.html"><a href="disenos-experimentales.html#diseno-de-experimentos"><i class="fa fa-check"></i><b>13.1.1</b> Diseño de experimentos</a></li>
<li class="chapter" data-level="13.1.2" data-path="disenos-experimentales.html"><a href="disenos-experimentales.html#elementos-de-los-disenos-de-bloques-al-azar"><i class="fa fa-check"></i><b>13.1.2</b> Elementos de los Diseños de Bloques al Azar</a></li>
<li class="chapter" data-level="13.1.3" data-path="disenos-experimentales.html"><a href="disenos-experimentales.html#criterios-para-definir-los-bloques"><i class="fa fa-check"></i><b>13.1.3</b> Criterios para definir los bloques</a></li>
<li class="chapter" data-level="13.1.4" data-path="disenos-experimentales.html"><a href="disenos-experimentales.html#ventajas-y-desventajas"><i class="fa fa-check"></i><b>13.1.4</b> Ventajas y desventajas</a></li>
<li class="chapter" data-level="13.1.5" data-path="disenos-experimentales.html"><a href="disenos-experimentales.html#modelo"><i class="fa fa-check"></i><b>13.1.5</b> Modelo</a></li>
</ul></li>
<li class="chapter" data-level="13.2" data-path="disenos-experimentales.html"><a href="disenos-experimentales.html#analisis-de-la-varianza-y-pruebas"><i class="fa fa-check"></i><b>13.2</b> Análisis de la varianza y pruebas</a><ul>
<li class="chapter" data-level="13.2.1" data-path="disenos-experimentales.html"><a href="disenos-experimentales.html#analisis-de-la-varianza"><i class="fa fa-check"></i><b>13.2.1</b> Análisis de la varianza</a></li>
<li class="chapter" data-level="13.2.2" data-path="disenos-experimentales.html"><a href="disenos-experimentales.html#prueba-de-tukey-de-aditividad"><i class="fa fa-check"></i><b>13.2.2</b> Prueba de Tukey de Aditividad</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="14" data-path="problemas-anova-diseno-experimental.html"><a href="problemas-anova-diseno-experimental.html"><i class="fa fa-check"></i><b>14</b> Problemas ANOVA Diseño Experimental</a><ul>
<li class="chapter" data-level="14.1" data-path="problemas-anova-diseno-experimental.html"><a href="problemas-anova-diseno-experimental.html#ejemplo-1"><i class="fa fa-check"></i><b>14.1</b> Ejemplo</a></li>
<li class="chapter" data-level="14.2" data-path="problemas-anova-diseno-experimental.html"><a href="problemas-anova-diseno-experimental.html#problemas-4"><i class="fa fa-check"></i><b>14.2</b> Problemas</a></li>
</ul></li>
<li class="chapter" data-level="15" data-path="pruebas-para-varias-muestras-pareadas.html"><a href="pruebas-para-varias-muestras-pareadas.html"><i class="fa fa-check"></i><b>15</b> Pruebas para varias muestras pareadas</a><ul>
<li class="chapter" data-level="15.1" data-path="pruebas-para-varias-muestras-pareadas.html"><a href="pruebas-para-varias-muestras-pareadas.html#prueba-de-friedman-para-varias-muestras-relacionadas"><i class="fa fa-check"></i><b>15.1</b> Prueba de Friedman para varias muestras relacionadas</a><ul>
<li class="chapter" data-level="15.1.1" data-path="pruebas-para-varias-muestras-pareadas.html"><a href="pruebas-para-varias-muestras-pareadas.html#estadistico"><i class="fa fa-check"></i><b>15.1.1</b> Estadístico</a></li>
<li class="chapter" data-level="15.1.2" data-path="pruebas-para-varias-muestras-pareadas.html"><a href="pruebas-para-varias-muestras-pareadas.html#supuestos-4"><i class="fa fa-check"></i><b>15.1.2</b> Supuestos</a></li>
<li class="chapter" data-level="15.1.3" data-path="pruebas-para-varias-muestras-pareadas.html"><a href="pruebas-para-varias-muestras-pareadas.html#hipotesis-5"><i class="fa fa-check"></i><b>15.1.3</b> Hipótesis</a></li>
<li class="chapter" data-level="15.1.4" data-path="pruebas-para-varias-muestras-pareadas.html"><a href="pruebas-para-varias-muestras-pareadas.html#comparaciones-multiples-1"><i class="fa fa-check"></i><b>15.1.4</b> Comparaciones múltiples</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="16" data-path="practico-de-pruebas-no-parametricas-para-muestras-relacionadas.html"><a href="practico-de-pruebas-no-parametricas-para-muestras-relacionadas.html"><i class="fa fa-check"></i><b>16</b> Práctico de Pruebas no paramétricas para muestras relacionadas</a><ul>
<li class="chapter" data-level="16.1" data-path="practico-de-pruebas-no-parametricas-para-muestras-relacionadas.html"><a href="practico-de-pruebas-no-parametricas-para-muestras-relacionadas.html#problemas-5"><i class="fa fa-check"></i><b>16.1</b> Problemas</a></li>
<li class="chapter" data-level="16.2" data-path="practico-de-pruebas-no-parametricas-para-muestras-relacionadas.html"><a href="practico-de-pruebas-no-parametricas-para-muestras-relacionadas.html#problema-4"><i class="fa fa-check"></i><b>16.2</b> Problema 4</a></li>
</ul></li>
<li class="chapter" data-level="17" data-path="regresion.html"><a href="regresion.html"><i class="fa fa-check"></i><b>17</b> Regresión</a><ul>
<li class="chapter" data-level="17.1" data-path="regresion.html"><a href="regresion.html#regresion-lineal-simple"><i class="fa fa-check"></i><b>17.1</b> Regresión Lineal Simple</a><ul>
<li class="chapter" data-level="17.1.1" data-path="regresion.html"><a href="regresion.html#intervalos-de-confianza"><i class="fa fa-check"></i><b>17.1.1</b> Intervalos de confianza</a></li>
</ul></li>
<li class="chapter" data-level="17.2" data-path="regresion.html"><a href="regresion.html#regresion-con-replicacion"><i class="fa fa-check"></i><b>17.2</b> Regresión con Replicación</a></li>
<li class="chapter" data-level="17.3" data-path="regresion.html"><a href="regresion.html#transformaciones-para-corregir-la-falta-de-linealidad"><i class="fa fa-check"></i><b>17.3</b> Transformaciones para corregir la falta de linealidad</a></li>
<li class="chapter" data-level="17.4" data-path="regresion.html"><a href="regresion.html#uso-de-los-residuales-para-comprobar-los-supuestos"><i class="fa fa-check"></i><b>17.4</b> Uso de los Residuales para Comprobar los Supuestos</a></li>
<li class="chapter" data-level="17.5" data-path="regresion.html"><a href="regresion.html#regresiones-multiples"><i class="fa fa-check"></i><b>17.5</b> Regresiones Múltiples</a></li>
</ul></li>
<li class="chapter" data-level="18" data-path="ancova.html"><a href="ancova.html"><i class="fa fa-check"></i><b>18</b> ANCOVA</a></li>
<li class="chapter" data-level="19" data-path="ordenacion-en-espacios-reducidos.html"><a href="ordenacion-en-espacios-reducidos.html"><i class="fa fa-check"></i><b>19</b> Ordenación en Espacios Reducidos</a><ul>
<li class="chapter" data-level="19.1" data-path="ordenacion-en-espacios-reducidos.html"><a href="ordenacion-en-espacios-reducidos.html#analisis-de-componentes-principales"><i class="fa fa-check"></i><b>19.1</b> Análisis de componentes principales</a><ul>
<li class="chapter" data-level="19.1.1" data-path="ordenacion-en-espacios-reducidos.html"><a href="ordenacion-en-espacios-reducidos.html#biplots"><i class="fa fa-check"></i><b>19.1.1</b> Biplots</a></li>
</ul></li>
<li class="chapter" data-level="19.2" data-path="ordenacion-en-espacios-reducidos.html"><a href="ordenacion-en-espacios-reducidos.html#componentes-principales-de-una-matriz-de-correlacion"><i class="fa fa-check"></i><b>19.2</b> Componentes principales de una matriz de correlación</a></li>
<li class="chapter" data-level="19.3" data-path="ordenacion-en-espacios-reducidos.html"><a href="ordenacion-en-espacios-reducidos.html#cuantos-componentes-son-significativos"><i class="fa fa-check"></i><b>19.3</b> ¿Cuantos componentes son significativos?</a></li>
<li class="chapter" data-level="19.4" data-path="ordenacion-en-espacios-reducidos.html"><a href="ordenacion-en-espacios-reducidos.html#mal-uso-de-los-componentes-principales"><i class="fa fa-check"></i><b>19.4</b> Mal uso de los componentes principales</a></li>
</ul></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Estadística Avanzada para Ciencias Naturales</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="ancova" class="section level1">
<h1><span class="header-section-number">Capítulo 18</span> ANCOVA</h1>
<p>ANOVA (Análisis de la Varianza) y regresión lineal aparentemente no tienen
relación entre sí. El primero se ocupa de variables explicatorias cualitativas,
mientras que el segundo de variables explicatorias cuantitativas. El análisis
de la Covarianza se ocupa de analizar datos con ambos tipos de variables.
De esta forma se obtiene una regresión entre la variable de respuesta y la
variable explicatoria cuantitativa por cada nivel de la variable explicatoria
cualitativa. Supongamos que deseamos modelar el peso de acuerdo a la edad y
el sexo. El modelo máximo tiene cuatro parámetros: dos ordenadas al origen, y
dos pendientes (una para machos y otra para hembras).</p>
<p><span class="math display">\[
 peso_{hembra} = a_{hembra} + b_{hembra} \times edad\\
 peso_{macho} = a_{macho} + b_{macho} \times edad
 \]</span></p>
<p>Como debe cumplirse con el principio de parsimonia hay que simplificar el
modelo lo más posible. En total hay seis modelos posibles, siendo el más
complejo el de cuatro parámetros. Puede ser que los necesitemos todos ellos.
El modelo de cuatro parámetros está representado en la Figura
<a href="ancova.html#fig:modelos-figura-ejemplo">18.1</a>-a. Otra forma puede ser que solo necesitemos un
solo parámetro de pendiente como en la Figura <a href="ancova.html#fig:modelos-figura-ejemplo">18.1</a>-b.
Otra opción, es que la ordenada al origen sean iguales pero la pendientes sean
diferentes, como en la Figura <a href="ancova.html#fig:modelos-figura-ejemplo">18.1</a>-c. Puede ser que
la edad no tenga efecto sobre el peso entonces pero que el sexo si tenga efecto
como en la Figura <a href="ancova.html#fig:modelos-figura-ejemplo">18.1</a>-d. Entonces este modelo tendrá
solo dos parámetros. También puede darse el caso opuesto, que la edad tenga
efecto sobre el peso pero no el sexo, como en la Figura
<a href="ancova.html#fig:modelos-figura-ejemplo">18.1</a>-e. La última opción es que ni la edad ni el sexo
tengan efecto sobre el peso, como en la Figura <a href="ancova.html#fig:modelos-figura-ejemplo">18.1</a>-f.
Este último modelo solo tendrá un parámetro.</p>
<div class="figure"><span id="fig:modelos-figura-ejemplo"></span>
<img src="ancova_files/figure-html/modelos-figura-ejemplo-1.png" alt="Varios modelos de ANCOVA con un número diferente de parámetros. a) Dos ordenadas al origen y dos pendientes. b) dos ordenadas al origen y una pendiente común. c) Una ordenada al origen y dos pendientes. d) Dos ordenadas al origen, sin pendiente. e) Una ordenada al origen y una pendiente. f) Una ordenada al origen, sin pendiente." width="672" />
<p class="caption">
Figura 18.1: Varios modelos de ANCOVA con un número diferente de parámetros. a) Dos ordenadas al origen y dos pendientes. b) dos ordenadas al origen y una pendiente común. c) Una ordenada al origen y dos pendientes. d) Dos ordenadas al origen, sin pendiente. e) Una ordenada al origen y una pendiente. f) Una ordenada al origen, sin pendiente.
</p>
</div>
<p>Como siempre, las decisión acerca de si conservar ambos parámetros o si son
significativos se realiza con pruebas de hipótesis.</p>
<p>Por ejemplo, se quiere ver cual es la capacidad de regeneración de las plantas
y producir semillas luego del pastoreo. Antes del pastoreo, se registró el
tamaño de la planta como el diámetro de la parte superior del rizoma. El
pastoreo tiene dos niveles: con pastoreo y sin pastoreo. La respuesta es el
peso de las semillas producidas. Es de esperar que las plantas más grandes
produzcan más semillas. Y que las plantas pastoreadas produzcan menos semillas
que las plantas no pastoreadas.</p>
<pre class="sourceCode r"><code class="sourceCode r">compensation &lt;-<span class="st"> </span><span class="kw">read_csv</span>(<span class="st">&quot;data/ipomopsis.csv&quot;</span>)
compensation</code></pre>
<pre><code>## # A tibble: 40 x 3
##     Root Fruit Grazing 
##    &lt;dbl&gt; &lt;dbl&gt; &lt;chr&gt;   
##  1  6.22  59.8 Ungrazed
##  2  6.49  61.0 Ungrazed
##  3  4.92  14.7 Ungrazed
##  4  5.13  19.3 Ungrazed
##  5  5.42  34.2 Ungrazed
##  6  5.36  35.5 Ungrazed
##  7  7.61  87.7 Ungrazed
##  8  6.35  63.2 Ungrazed
##  9  4.97  24.2 Ungrazed
## 10  6.93  64.3 Ungrazed
## # ... with 30 more rows</code></pre>
<p>Los datos tienen tres columnas, la primera <code>Root</code> corresponde al tamaño del
rizoma en centímetros. <code>Fruit</code> corresponde al peso de semillas en gramos. Y
por último, <code>Grazing</code> corresponde a si las plantas fueron pastoreadas <code>Grazed</code>
o no <code>Ungrazed</code>.</p>
<pre class="sourceCode r"><code class="sourceCode r"><span class="kw">ggplot</span>(compensation, <span class="kw">aes</span>(<span class="dt">x =</span> Root, <span class="dt">y =</span> Fruit)) <span class="op">+</span><span class="st"> </span>
<span class="st">  </span><span class="kw">geom_point</span>()</code></pre>
<div class="figure"><span id="fig:root-fruit"></span>
<img src="ancova_files/figure-html/root-fruit-1.png" alt="Diagrama de dispersión entre el tamaño del rizoma y el peso de las semillas" width="672" />
<p class="caption">
Figura 18.2: Diagrama de dispersión entre el tamaño del rizoma y el peso de las semillas
</p>
</div>
<p>La Figura <a href="ancova.html#fig:root-fruit">18.2</a> muestra que las plantas más grandes produjeron
más semillas, tal y como se esperaba.</p>
<p>¿Y qué pasó con el nivel de pastoreo? En la Figura <a href="ancova.html#fig:grazed-fruit">18.3</a> los
resultados no son tan claros. La línea se corresponde a la media de cada grupo
y muestra que ¡Las plantas pastoreadas producen más semillas que las no
pasteoreadas! Un resultado completamente sorpredente, y contrario a lo
esperado ¿Esto será así realmente o habrá alguna explicación?</p>
<pre class="sourceCode r"><code class="sourceCode r"><span class="kw">ggplot</span>(compensation, <span class="kw">aes</span>(<span class="dt">x =</span> Grazing, <span class="dt">y =</span> Fruit)) <span class="op">+</span><span class="st"> </span>
<span class="st">  </span><span class="kw">geom_point</span>() <span class="op">+</span><span class="st"> </span>
<span class="st">  </span><span class="kw">stat_summary</span>(<span class="dt">fun.y =</span> mean, <span class="dt">fun.ymin =</span> mean, <span class="dt">fun.ymax =</span> mean,
                 <span class="dt">geom =</span> <span class="st">&quot;crossbar&quot;</span>, <span class="dt">width =</span> <span class="fl">0.2</span>)</code></pre>
<div class="figure"><span id="fig:grazed-fruit"></span>
<img src="ancova_files/figure-html/grazed-fruit-1.png" alt="Datos de niveles de pastoreo y peso de semillas, la barra representa la media." width="672" />
<p class="caption">
Figura 18.3: Datos de niveles de pastoreo y peso de semillas, la barra representa la media.
</p>
</div>
<p>El modelo más complejo incluye cuatro parámetros. Dos ordenadas al origen
y dos pendientes.</p>
<p><span class="math display">\[
 Fruit_{grazed} = a_{grazed} + b_{grazed} \times Root\\
 Fruit_{ungrazed} = a_{ungrazed} + b_{ungrazed} \times Root
 \]</span>
Ajustando este modelo en <em>R</em> es parecido a hacer un modelo de regresión usando
la función <code>lm()</code></p>
<pre class="sourceCode r"><code class="sourceCode r">semillas_completo &lt;-<span class="st"> </span><span class="kw">lm</span>(Fruit <span class="op">~</span><span class="st"> </span>Grazing <span class="op">+</span><span class="st"> </span>Root <span class="op">+</span><span class="st"> </span>Grazing<span class="op">:</span>Root, <span class="dt">data =</span> compensation)</code></pre>
<p>Solo vamos a ver modelos de ANCOVA simples con una variable cualitativa y otra
cuantitativa. Como es el caso de una interacción entre una variable
cualitativa y otra cuantitativa, el resultado es que haya varias pendientes.
Una por cada nivel de la variable cualitativa. Veamos cual es el resultado de
este análisis:</p>
<pre class="sourceCode r"><code class="sourceCode r"><span class="kw">summary</span>(semillas_completo)</code></pre>
<pre><code>## 
## Call:
## lm(formula = Fruit ~ Grazing + Root + Grazing:Root, data = compensation)
## 
## Residuals:
##      Min       1Q   Median       3Q      Max 
## -17.3177  -2.8320   0.1247   3.8511  17.1313 
## 
## Coefficients:
##                      Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)          -125.173     12.811  -9.771 1.15e-11 ***
## GrazingUngrazed        30.806     16.842   1.829   0.0757 .  
## Root                   23.240      1.531  15.182  &lt; 2e-16 ***
## GrazingUngrazed:Root    0.756      2.354   0.321   0.7500    
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 6.831 on 36 degrees of freedom
## Multiple R-squared:  0.9293, Adjusted R-squared:  0.9234 
## F-statistic: 157.6 on 3 and 36 DF,  p-value: &lt; 2.2e-16</code></pre>
<p>Empezando a leer los resultados desde abajo, vemos que el modelo es
significativo. Es decir, al menos uno de los parámetros es distinto de 0. Y que
ajuste de los datos al modelo parece ser muy bueno, el R<sup>2</sup> ajustado es mayor a
90%.</p>
<p>Más arriba tenemos los coeficientes del modelo. Recordemos que en <em>R</em> obtenemos
los coeficientes obtenemos son solo el valor real para la primera vez que
aparece. Luego debemos obtener el valor del parámetro como la suma del
parámetro principal y el efecto del nivel. Para aclarar, reemplazando la
ecuación con los valores de <span class="math inline">\(a\)</span> y <span class="math inline">\(b\)</span> para cada una de las ecuaciones. El
primer valor, <code>(Intercept)</code> corresponde a la ordenada al origen para <em>Grazed</em>
Esto es así porque el primer nivel del un factor va a ser el que sea asignado
a <code>(Intercept)</code> y va a correponder a nivel de base para la determinación de
la pendiente. Por lo tanto, el coeficiente de <code>Root</code> que vemos corresponde
también al nivel <em>Grazed</em></p>
<p><span class="math display">\[
 Fruit_{grazed} = -125.173 + 23.24 \times Root\\
 \]</span>
Completar la ecuación para el nivel <em>Ungrazed</em> es un poco más complicado porque
lo que vemos es el efecto del nivel y no el parámetro. El efecto de los otros
niveles aparece como el nombre del factor seguido por el nombre del nivel.
En nuestro ejemplo, <em>Grazing</em> es el factor, el nivel es <em>Ungrazed</em> y aparece
como <code>GrazedUngrazed</code> en los coeficientes. Por otro lado, el efecto de
<em>Ungrazed</em> sobre la pendiente aparece como la interacción entre
<code>GrazedUngrazed</code> y <code>Root</code>.</p>
<p><span class="math display">\[
 Fruit_{ungrazed} = \left(-125.173 + 30.806\right) + \left( 23.24 + 0.756\right)\times Root \\ 
 Fruit_{ungrazed} = \left(-94.367\right) + \left( `r23.24 + 0.756`\right)\times Root \\ 
 \]</span>
Por otro lado, debemos considerar si debemos conservar todos esos parámetros o
si podemos poner algún parametro en común. Empezemos por ver si las pendientes
son distintas. Esto implica, realizar un nuevo modelo
con una pendiente común para las plantas <em>Grazed</em> y <em>Ungrazed</em>:</p>
<p><span class="math display">\[
 Fruit_{grazed} = a_{grazed} + b \times Root\\
 Fruit_{ungrazed} = a_{ungrazed} + b \times Root
 \]</span></p>
<p>Ajustarlo en <em>R</em> es como hacerlo en el caso anterior pero eliminando la
interacción en la formula.</p>
<pre class="sourceCode r"><code class="sourceCode r">semillas_pendiente_comun &lt;-<span class="st"> </span><span class="kw">lm</span>(Fruit <span class="op">~</span><span class="st"> </span>Grazing <span class="op">+</span><span class="st"> </span>Root, <span class="dt">data =</span> compensation)</code></pre>
<p>Para comprobar si el modelo más simple debe ser preferido usamos la
función <code>anova()</code> para comprobar si el modelo más complejo es
significativamente diferente del más simple. De no serlo, debemos descartarlo
y quedarnos con el más simple.</p>
<pre class="sourceCode r"><code class="sourceCode r"><span class="kw">anova</span>(semillas_completo, semillas_pendiente_comun)</code></pre>
<pre><code>## Analysis of Variance Table
## 
## Model 1: Fruit ~ Grazing + Root + Grazing:Root
## Model 2: Fruit ~ Grazing + Root
##   Res.Df    RSS Df Sum of Sq      F Pr(&gt;F)
## 1     36 1679.7                           
## 2     37 1684.5 -1   -4.8122 0.1031   0.75</code></pre>
<p>Vemos que diferencia es muy pequeña, con un estadístico <em>F</em> asociado muy
pequeño de 0.1031 y una probablidad de un <em>F</em> mayor de 0.75. Por lo tanto,
no hay diferencias significativas entre los modelos, descartando el más
complejo.</p>
<p>Para ver los coeficientes usamos <code>summary()</code></p>
<pre class="sourceCode r"><code class="sourceCode r"><span class="kw">summary</span>(semillas_pendiente_comun)</code></pre>
<pre><code>## 
## Call:
## lm(formula = Fruit ~ Grazing + Root, data = compensation)
## 
## Residuals:
##      Min       1Q   Median       3Q      Max 
## -17.1920  -2.8224   0.3223   3.9144  17.3290 
## 
## Coefficients:
##                 Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)     -127.829      9.664  -13.23 1.35e-15 ***
## GrazingUngrazed   36.103      3.357   10.75 6.11e-13 ***
## Root              23.560      1.149   20.51  &lt; 2e-16 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 6.747 on 37 degrees of freedom
## Multiple R-squared:  0.9291, Adjusted R-squared:  0.9252 
## F-statistic: 242.3 on 2 and 37 DF,  p-value: &lt; 2.2e-16</code></pre>
<p>Volviendo a leer los coeficientes vemos que todos son significativos ya que
el valor del estadístico <em>t</em> asociado a cada uno es menor al 0.05.
Por lo tanto, hay un efecto del tamaño del rizoma que es común a todas las
plantas y hay diferencias significativas entre las plantas pastoreados y las
no pastoreadas. ¿Cuales producen más semillas? Viendo el signo positivo del
efecto de las plantas no pastoreadas (<em>GrazingUngrazed</em>) es posible deducir que
ellas son las que producen más semillas. La formula para cada una de las
rectas es:</p>
<p><span class="math display">\[
  Fruit_{grazed} = -127.829 +  23.56 \times Root \\ 
  Fruit_{ungrazed} = \left(-127.829 + 36.103\right) + 23.56 \times Root  \\ 
 Fruit_{ungrazed} = \left(-91.726\right) + 23.56 \times Root  
 \]</span></p>
<div class="figure"><span id="fig:fig-modelo-final"></span>
<img src="ancova_files/figure-html/fig-modelo-final-1.png" alt="Gráfico de dispersión entre el tamaño del rizoma y el peso de las semillas. Se muestra la línea de regresión estimada por el modelo ANCOVA final." width="672" />
<p class="caption">
Figura 18.4: Gráfico de dispersión entre el tamaño del rizoma y el peso de las semillas. Se muestra la línea de regresión estimada por el modelo ANCOVA final.
</p>
</div>
<p>Viendo la Figura <a href="ancova.html#fig:fig-modelo-final">18.4</a> resulta claro porque el resultado de que las plantas
pastoreadas producian más semillas era engañoso. Las plantas pastoreadas eran
más grandes, y el tamaño de la planta estaba oscurenciendo el resultado.</p>
<p>Si no hubiesemos tenido en cuenta el tamaño, habríamos llegado a la conclusión
equivocada. Realizando la prueba estadística sobre el modelo incorrecto
llegariamos a la conclusión de que efectivamente el pastoreo aumenta la
producción de semillas.</p>
<pre class="sourceCode r"><code class="sourceCode r"><span class="kw">anova</span>(<span class="kw">lm</span>(Fruit <span class="op">~</span><span class="st"> </span>Grazing, <span class="dt">data =</span> compensation))</code></pre>
<pre><code>## Analysis of Variance Table
## 
## Response: Fruit
##           Df  Sum Sq Mean Sq F value  Pr(&gt;F)  
## Grazing    1  2910.4 2910.44  5.3086 0.02678 *
## Residuals 38 20833.4  548.25                  
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<p>Usando el modelo correcto vemos que la media de las plantas no pastoreadas
es mayor que las pastereadas (41.35 vs 77.46):</p>
<pre class="sourceCode r"><code class="sourceCode r"><span class="kw">summary</span>(<span class="kw">emmeans</span>(semillas_pendiente_comun, <span class="op">~</span>Grazing)) </code></pre>
<pre><code>##  Grazing    emmean       SE df lower.CL upper.CL
##  Grazed   41.35888 1.989014 37 37.32875 45.38900
##  Ungrazed 77.46212 1.989014 37 73.43200 81.49225
## 
## Confidence level used: 0.95</code></pre>
<p>Esto se obtiene usando la formula en la media de <em>Root</em>.</p>
<p><span class="math display">\[
 Fruit_{grazed} = -127.829 +  23.56 \times \overline{Root} \\ 
 Fruit_{ungrazed} = \left(-91.726\right) + 23.56 \times \overline{Root}\\
 Fruit_{grazed} = -127.829 +  23.56 \times 7.18115 \\ 
 Fruit_{ungrazed} = \left(-91.726\right) + 23.56 \times 7.18115\\
  Fruit_{grazed} = 41.358894 \\ 
 Fruit_{ungrazed} = 77.461894
 \]</span></p>

</div>
            </section>

          </div>
        </div>
      </div>
<a href="regresion.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="ordenacion-en-espacios-reducidos.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/lunr.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"google": false,
"linkedin": false,
"weibo": false,
"instapper": false,
"vk": false,
"all": ["facebook", "google", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": "https://github.com/rstudio/bookdown-demo/edit/master/ancova.Rmd",
"text": "Edit"
},
"download": ["EACN.pdf", "EACN.epub"],
"toc": {
"collapse": "subsection"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://cdn.bootcss.com/mathjax/2.7.1/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:" && /^https?:/.test(src))
      src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
