<!DOCTYPE html>
<html >

<head>

  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title>Estadística Avanzada para Ciencias Naturales</title>
  <meta name="description" content="Un libro con la teoría, ejemplos y práctica de Estadística Avanzada para Ciencias Naturales.">
  <meta name="generator" content="bookdown 0.7.7 and GitBook 2.6.7">

  <meta property="og:title" content="Estadística Avanzada para Ciencias Naturales" />
  <meta property="og:type" content="book" />
  
  
  <meta property="og:description" content="Un libro con la teoría, ejemplos y práctica de Estadística Avanzada para Ciencias Naturales." />
  

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Estadística Avanzada para Ciencias Naturales" />
  
  <meta name="twitter:description" content="Un libro con la teoría, ejemplos y práctica de Estadística Avanzada para Ciencias Naturales." />
  

<meta name="author" content="Dr. Luciano Selzer">


<meta name="date" content="2018-04-13">

  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-status-bar-style" content="black">
  
  
<link rel="prev" href="practico-de-pruebas-no-parametricas-para-muestras-relacionadas.html">
<link rel="next" href="ordenacion-en-espacios-reducidos.html">
<script src="libs/jquery-2.2.3/jquery.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />









<style type="text/css">
a.sourceLine { display: inline-block; line-height: 1.25; }
a.sourceLine { pointer-events: none; color: inherit; text-decoration: inherit; }
a.sourceLine:empty { height: 1.2em; position: absolute; }
.sourceCode { overflow: visible; }
code.sourceCode { white-space: pre; position: relative; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
code.sourceCode { white-space: pre-wrap; }
a.sourceLine { text-indent: -1em; padding-left: 1em; }
}
pre.numberSource a.sourceLine
  { position: relative; }
pre.numberSource a.sourceLine:empty
  { position: absolute; }
pre.numberSource a.sourceLine::before
  { content: attr(data-line-number);
    position: absolute; left: -5em; text-align: right; vertical-align: baseline;
    border: none; pointer-events: all;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {  }
@media screen {
a.sourceLine::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">Laboratorios de Estadística Avanzada</a></li>

<li class="divider"></li>
<li class="chapter" data-level="1" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i><b>1</b> Reglamento</a><ul>
<li class="chapter" data-level="1.1" data-path="index.html"><a href="index.html#asistencia-a-clases-participacion-y-evaluacion-de-pares"><i class="fa fa-check"></i><b>1.1</b> Asistencia a clases, participación y evaluación de pares</a></li>
<li class="chapter" data-level="1.2" data-path="index.html"><a href="index.html#entrega-de-ejercicios"><i class="fa fa-check"></i><b>1.2</b> Entrega de Ejercicios</a></li>
<li class="chapter" data-level="1.3" data-path="index.html"><a href="index.html#laboratorios"><i class="fa fa-check"></i><b>1.3</b> Laboratorios</a></li>
<li class="chapter" data-level="1.4" data-path="index.html"><a href="index.html#cuestionario-de-comprension"><i class="fa fa-check"></i><b>1.4</b> Cuestionario de Comprensión</a></li>
<li class="chapter" data-level="1.5" data-path="index.html"><a href="index.html#parciales"><i class="fa fa-check"></i><b>1.5</b> Parciales</a></li>
<li class="chapter" data-level="1.6" data-path="index.html"><a href="index.html#cronograma"><i class="fa fa-check"></i><b>1.6</b> Cronograma</a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="introduccion-a-r-y-rstudio.html"><a href="introduccion-a-r-y-rstudio.html"><i class="fa fa-check"></i><b>2</b> Introducción a <em>R</em> y RStudio</a><ul>
<li class="chapter" data-level="2.1" data-path="introduccion-a-r-y-rstudio.html"><a href="introduccion-a-r-y-rstudio.html#rstudio"><i class="fa fa-check"></i><b>2.1</b> RStudio</a></li>
<li class="chapter" data-level="2.2" data-path="introduccion-a-r-y-rstudio.html"><a href="introduccion-a-r-y-rstudio.html#analisis-reproducible"><i class="fa fa-check"></i><b>2.2</b> Análisis Reproducible</a><ul>
<li class="chapter" data-level="2.2.1" data-path="introduccion-a-r-y-rstudio.html"><a href="introduccion-a-r-y-rstudio.html#rmarkdown"><i class="fa fa-check"></i><b>2.2.1</b> Rmarkdown</a></li>
</ul></li>
<li class="chapter" data-level="2.3" data-path="introduccion-a-r-y-rstudio.html"><a href="introduccion-a-r-y-rstudio.html#integrando-codigo"><i class="fa fa-check"></i><b>2.3</b> Integrando código</a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="visualizacion-de-datos.html"><a href="visualizacion-de-datos.html"><i class="fa fa-check"></i><b>3</b> Visualización de Datos</a><ul>
<li class="chapter" data-level="3.1" data-path="visualizacion-de-datos.html"><a href="visualizacion-de-datos.html#introduccion"><i class="fa fa-check"></i><b>3.1</b> Introducción</a></li>
<li class="chapter" data-level="3.2" data-path="visualizacion-de-datos.html"><a href="visualizacion-de-datos.html#el-conjunto-de-datos-mpg"><i class="fa fa-check"></i><b>3.2</b> El conjunto de datos <code>mpg</code></a></li>
<li class="chapter" data-level="3.3" data-path="visualizacion-de-datos.html"><a href="visualizacion-de-datos.html#graficos-con-ggplot"><i class="fa fa-check"></i><b>3.3</b> Gráficos con ggplot</a></li>
<li class="chapter" data-level="3.4" data-path="visualizacion-de-datos.html"><a href="visualizacion-de-datos.html#mapeando"><i class="fa fa-check"></i><b>3.4</b> Mapeando</a></li>
<li class="chapter" data-level="3.5" data-path="visualizacion-de-datos.html"><a href="visualizacion-de-datos.html#formas-geometricas"><i class="fa fa-check"></i><b>3.5</b> Formas geometricas</a></li>
<li class="chapter" data-level="3.6" data-path="visualizacion-de-datos.html"><a href="visualizacion-de-datos.html#transformaciones-estadisticas"><i class="fa fa-check"></i><b>3.6</b> Transformaciones Estadísticas</a></li>
<li class="chapter" data-level="3.7" data-path="visualizacion-de-datos.html"><a href="visualizacion-de-datos.html#ajuste-de-posiciones"><i class="fa fa-check"></i><b>3.7</b> Ajuste de Posiciones</a></li>
<li class="chapter" data-level="3.8" data-path="visualizacion-de-datos.html"><a href="visualizacion-de-datos.html#sistemas-de-coordenadas"><i class="fa fa-check"></i><b>3.8</b> Sistemas de Coordenadas</a></li>
<li class="chapter" data-level="3.9" data-path="visualizacion-de-datos.html"><a href="visualizacion-de-datos.html#personalizando-el-grafico"><i class="fa fa-check"></i><b>3.9</b> Personalizando el gráfico</a></li>
</ul></li>
<li class="chapter" data-level="4" data-path="manejo-de-datos.html"><a href="manejo-de-datos.html"><i class="fa fa-check"></i><b>4</b> Manejo de datos</a><ul>
<li class="chapter" data-level="4.1" data-path="manejo-de-datos.html"><a href="manejo-de-datos.html#seleccionando-datos"><i class="fa fa-check"></i><b>4.1</b> Seleccionando datos</a></li>
<li class="chapter" data-level="4.2" data-path="manejo-de-datos.html"><a href="manejo-de-datos.html#seleccionando-columnas"><i class="fa fa-check"></i><b>4.2</b> Seleccionando columnas</a></li>
<li class="chapter" data-level="4.3" data-path="manejo-de-datos.html"><a href="manejo-de-datos.html#agregando-columnas"><i class="fa fa-check"></i><b>4.3</b> Agregando columnas</a></li>
<li class="chapter" data-level="4.4" data-path="manejo-de-datos.html"><a href="manejo-de-datos.html#operaciones-por-grupos"><i class="fa fa-check"></i><b>4.4</b> Operaciones por grupos</a></li>
<li class="chapter" data-level="4.5" data-path="manejo-de-datos.html"><a href="manejo-de-datos.html#formato-ancho-y-formato-largo"><i class="fa fa-check"></i><b>4.5</b> Formato Ancho y Formato Largo</a></li>
<li class="chapter" data-level="4.6" data-path="manejo-de-datos.html"><a href="manejo-de-datos.html#por-su-cuenta"><i class="fa fa-check"></i><b>4.6</b> Por su cuenta</a></li>
</ul></li>
<li class="chapter" data-level="5" data-path="anova.html"><a href="anova.html"><i class="fa fa-check"></i><b>5</b> ANOVA</a><ul>
<li class="chapter" data-level="5.1" data-path="anova.html"><a href="anova.html#algunos-conceptos-importantes"><i class="fa fa-check"></i><b>5.1</b> Algunos conceptos importantes</a></li>
<li class="chapter" data-level="5.2" data-path="anova.html"><a href="anova.html#diseno-de-estudios-de-anova"><i class="fa fa-check"></i><b>5.2</b> Diseño de Estudios de ANOVA</a></li>
<li class="chapter" data-level="5.3" data-path="anova.html"><a href="anova.html#planificacion-de-experimentos"><i class="fa fa-check"></i><b>5.3</b> Planificación De Experimentos</a></li>
<li class="chapter" data-level="5.4" data-path="anova.html"><a href="anova.html#usos-del-anova"><i class="fa fa-check"></i><b>5.4</b> Usos Del ANOVA</a></li>
<li class="chapter" data-level="5.5" data-path="anova.html"><a href="anova.html#modelo-i-de-anova.-niveles-del-factor-fijos"><i class="fa fa-check"></i><b>5.5</b> MODELO I DE ANOVA. NIVELES DEL FACTOR FIJOS</a><ul>
<li class="chapter" data-level="5.5.1" data-path="anova.html"><a href="anova.html#distincion-entre-modelos-i-y-ii-de-anova"><i class="fa fa-check"></i><b>5.5.1</b> Distinción Entre Modelos I Y II de ANOVA</a></li>
<li class="chapter" data-level="5.5.2" data-path="anova.html"><a href="anova.html#ideas-basicas"><i class="fa fa-check"></i><b>5.5.2</b> Ideas Básicas</a></li>
</ul></li>
<li class="chapter" data-level="5.6" data-path="anova.html"><a href="anova.html#comprobacion-de-los-supuestos"><i class="fa fa-check"></i><b>5.6</b> Comprobación de los Supuestos</a><ul>
<li class="chapter" data-level="5.6.1" data-path="anova.html"><a href="anova.html#prueba-para-igualdad-de-varianzas"><i class="fa fa-check"></i><b>5.6.1</b> Prueba para igualdad de varianzas</a></li>
<li class="chapter" data-level="5.6.2" data-path="anova.html"><a href="anova.html#prueba-de-kolmogorov---smirnov-modificacion-de-lilliefors-para-estudiar-normalidad"><i class="fa fa-check"></i><b>5.6.2</b> Prueba de Kolmogorov - Smirnov (modificación de Lilliefors) para estudiar Normalidad</a></li>
<li class="chapter" data-level="5.6.3" data-path="anova.html"><a href="anova.html#residuos"><i class="fa fa-check"></i><b>5.6.3</b> Residuos</a></li>
<li class="chapter" data-level="5.6.4" data-path="anova.html"><a href="anova.html#graficos-de-residuos"><i class="fa fa-check"></i><b>5.6.4</b> Gráficos de Residuos</a></li>
</ul></li>
<li class="chapter" data-level="5.7" data-path="anova.html"><a href="anova.html#transformaciones"><i class="fa fa-check"></i><b>5.7</b> Transformaciones</a><ul>
<li class="chapter" data-level="5.7.1" data-path="anova.html"><a href="anova.html#transformaciones-para-estabilizar-las-varianzas"><i class="fa fa-check"></i><b>5.7.1</b> Transformaciones para estabilizar las Varianzas</a></li>
<li class="chapter" data-level="5.7.2" data-path="anova.html"><a href="anova.html#transformaciones-para-corregir-la-falta-de-normalidad"><i class="fa fa-check"></i><b>5.7.2</b> Transformaciones para corregir la falta de normalidad</a></li>
<li class="chapter" data-level="5.7.3" data-path="anova.html"><a href="anova.html#efectos-del-alejamiento-de-los-supuestos-del-modelo"><i class="fa fa-check"></i><b>5.7.3</b> Efectos Del Alejamiento De Los Supuestos Del Modelo</a></li>
</ul></li>
<li class="chapter" data-level="5.8" data-path="anova.html"><a href="anova.html#formulacion-del-modelo-i-de-anova."><i class="fa fa-check"></i><b>5.8</b> Formulación Del Modelo I De ANOVA.</a><ul>
<li class="chapter" data-level="5.8.1" data-path="anova.html"><a href="anova.html#caracteristicas-importantes-del-modelo"><i class="fa fa-check"></i><b>5.8.1</b> Características importantes del modelo</a></li>
<li class="chapter" data-level="5.8.2" data-path="anova.html"><a href="anova.html#interpretacion-de-las-medias-de-los-niveles-del-factor"><i class="fa fa-check"></i><b>5.8.2</b> Interpretación De Las Medias De Los Niveles Del Factor</a></li>
<li class="chapter" data-level="5.8.3" data-path="anova.html"><a href="anova.html#ajustando-el-modelo"><i class="fa fa-check"></i><b>5.8.3</b> Ajustando El Modelo</a></li>
<li class="chapter" data-level="5.8.4" data-path="anova.html"><a href="anova.html#estimadores-de-minimos-cuadrados"><i class="fa fa-check"></i><b>5.8.4</b> Estimadores De Mínimos Cuadrados</a></li>
</ul></li>
<li class="chapter" data-level="5.9" data-path="anova.html"><a href="anova.html#particion-de-la-suma-de-cuadrados-total"><i class="fa fa-check"></i><b>5.9</b> Partición De La Suma De Cuadrados Total</a><ul>
<li class="chapter" data-level="5.9.1" data-path="anova.html"><a href="anova.html#formulas-computatorias"><i class="fa fa-check"></i><b>5.9.1</b> Fórmulas computatorias</a></li>
</ul></li>
<li class="chapter" data-level="5.10" data-path="anova.html"><a href="anova.html#grados-de-libertad"><i class="fa fa-check"></i><b>5.10</b> Grados De Libertad</a></li>
<li class="chapter" data-level="5.11" data-path="anova.html"><a href="anova.html#cuadrados-medios"><i class="fa fa-check"></i><b>5.11</b> Cuadrados Medios</a><ul>
<li class="chapter" data-level="5.11.1" data-path="anova.html"><a href="anova.html#esperanza-de-los-cuadrados-medios"><i class="fa fa-check"></i><b>5.11.1</b> Esperanza de los Cuadrados Medios</a></li>
<li class="chapter" data-level="5.11.2" data-path="anova.html"><a href="anova.html#comentarios-1"><i class="fa fa-check"></i><b>5.11.2</b> Comentarios</a></li>
</ul></li>
<li class="chapter" data-level="5.12" data-path="anova.html"><a href="anova.html#prueba-f-para-la-igualdad-de-las-medias-de-los-niveles-del-factor"><i class="fa fa-check"></i><b>5.12</b> Prueba F para la Igualdad de las Medias de los Niveles del Factor</a><ul>
<li class="chapter" data-level="5.12.1" data-path="anova.html"><a href="anova.html#prueba-estadistica"><i class="fa fa-check"></i><b>5.12.1</b> Prueba Estadística</a></li>
<li class="chapter" data-level="5.12.2" data-path="anova.html"><a href="anova.html#distribucion-de-mathbffmathbf"><i class="fa fa-check"></i><b>5.12.2</b> Distribución de <span class="math inline">\(\mathbf{F}^{\mathbf{*}}\)</span></a></li>
<li class="chapter" data-level="5.12.3" data-path="anova.html"><a href="anova.html#regla-de-decision"><i class="fa fa-check"></i><b>5.12.3</b> Regla De Decisión</a></li>
<li class="chapter" data-level="5.12.4" data-path="anova.html"><a href="anova.html#comentario"><i class="fa fa-check"></i><b>5.12.4</b> Comentario</a></li>
</ul></li>
<li class="chapter" data-level="5.13" data-path="anova.html"><a href="anova.html#formulacion-alternativa-del-modelo-i"><i class="fa fa-check"></i><b>5.13</b> Formulación Alternativa Del Modelo I</a><ul>
<li class="chapter" data-level="5.13.1" data-path="anova.html"><a href="anova.html#definicion-de-mathbfmu_mathbfbullet"><i class="fa fa-check"></i><b>5.13.1</b> Definición de <span class="math inline">\(\mathbf{\mu}_{\mathbf{\bullet}}\)</span></a></li>
</ul></li>
<li class="chapter" data-level="5.14" data-path="anova.html"><a href="anova.html#prueba-para-la-igualdad-de-las-medias-de-los-niveles-del-factor"><i class="fa fa-check"></i><b>5.14</b> Prueba Para La Igualdad De Las Medias De Los Niveles Del Factor</a></li>
<li class="chapter" data-level="5.15" data-path="anova.html"><a href="anova.html#analisis-de-los-efectos-del-nivel-del-factor"><i class="fa fa-check"></i><b>5.15</b> Análisis De Los Efectos Del Nivel Del Factor</a><ul>
<li class="chapter" data-level="5.15.1" data-path="anova.html"><a href="anova.html#graficos-de-las-estimaciones-de-las-medias-de-los-niveles-del-factor"><i class="fa fa-check"></i><b>5.15.1</b> Gráficos de las estimaciones de las medias de los niveles del factor</a></li>
<li class="chapter" data-level="5.15.2" data-path="anova.html"><a href="anova.html#estimacion-de-los-efectos-de-los-niveles-del-factor"><i class="fa fa-check"></i><b>5.15.2</b> Estimación de los efectos de los niveles del factor</a></li>
<li class="chapter" data-level="5.15.3" data-path="anova.html"><a href="anova.html#comparaciones-multiples"><i class="fa fa-check"></i><b>5.15.3</b> Comparaciones múltiples</a></li>
</ul></li>
<li class="chapter" data-level="5.16" data-path="anova.html"><a href="anova.html#planificacion-del-tamano-muestral"><i class="fa fa-check"></i><b>5.16</b> Planificación Del Tamaño Muestral</a><ul>
<li class="chapter" data-level="5.16.1" data-path="anova.html"><a href="anova.html#potencia-de-la-prueba-f"><i class="fa fa-check"></i><b>5.16.1</b> Potencia De La Prueba F</a></li>
</ul></li>
<li class="chapter" data-level="5.17" data-path="anova.html"><a href="anova.html#modelo-ii-de-anova-niveles-del-factor-aleatorios"><i class="fa fa-check"></i><b>5.17</b> Modelo II De ANOVA: Niveles Del Factor Aleatorios</a><ul>
<li class="chapter" data-level="5.17.1" data-path="anova.html"><a href="anova.html#modelo-aleatorio-de-medias-de-celdas."><i class="fa fa-check"></i><b>5.17.1</b> Modelo Aleatorio de Medias de Celdas.</a></li>
<li class="chapter" data-level="5.17.2" data-path="anova.html"><a href="anova.html#caracteristicas-importantes-del-modelo-1"><i class="fa fa-check"></i><b>5.17.2</b> Características importantes del Modelo</a></li>
<li class="chapter" data-level="5.17.3" data-path="anova.html"><a href="anova.html#cuestiones-de-interes"><i class="fa fa-check"></i><b>5.17.3</b> Cuestiones de Interés</a></li>
<li class="chapter" data-level="5.17.4" data-path="anova.html"><a href="anova.html#prueba-para-mathbfsigma_mathbfmumathbf2-0"><i class="fa fa-check"></i><b>5.17.4</b> Prueba para <span class="math inline">\(\mathbf{\sigma}_{\mathbf{\mu}}^{\mathbf{2}}\)</span> = 0</a></li>
<li class="chapter" data-level="5.17.5" data-path="anova.html"><a href="anova.html#estimacion-de-mathbfmu_mathbfbullet"><i class="fa fa-check"></i><b>5.17.5</b> Estimación De <span class="math inline">\(\mathbf{\mu}_{\mathbf{\bullet}}\)</span></a></li>
<li class="chapter" data-level="5.17.6" data-path="anova.html"><a href="anova.html#estimacion-de-sigma_mu2left-sigma_mu2sigma2-right"><i class="fa fa-check"></i><b>5.17.6</b> Estimación De <span class="math inline">\(\sigma_{\mu}^2/\left ( \sigma_{\mu}^2+\sigma^2 \right )\)</span></a></li>
<li class="chapter" data-level="5.17.7" data-path="anova.html"><a href="anova.html#modelo-de-efectos-aleatorios"><i class="fa fa-check"></i><b>5.17.7</b> Modelo De Efectos Aleatorios</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="6" data-path="problemas-anova-simple.html"><a href="problemas-anova-simple.html"><i class="fa fa-check"></i><b>6</b> Problemas ANOVA Simple</a><ul>
<li class="chapter" data-level="6.0.1" data-path="problemas-anova-simple.html"><a href="problemas-anova-simple.html#recordatorio"><i class="fa fa-check"></i><b>6.0.1</b> Recordatorio</a></li>
<li class="chapter" data-level="6.1" data-path="problemas-anova-simple.html"><a href="problemas-anova-simple.html#problemas"><i class="fa fa-check"></i><b>6.1</b> Problemas</a><ul>
<li class="chapter" data-level="6.1.1" data-path="problemas-anova-simple.html"><a href="problemas-anova-simple.html#contrastes"><i class="fa fa-check"></i><b>6.1.1</b> Contrastes</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="7" data-path="anova-de-dos-factores.html"><a href="anova-de-dos-factores.html"><i class="fa fa-check"></i><b>7</b> ANOVA DE DOS FACTORES</a><ul>
<li class="chapter" data-level="7.1" data-path="anova-de-dos-factores.html"><a href="anova-de-dos-factores.html#ventajas-de-los-estudios-multifactoriales"><i class="fa fa-check"></i><b>7.1</b> Ventajas de los estudios multifactoriales</a><ul>
<li class="chapter" data-level="7.1.1" data-path="anova-de-dos-factores.html"><a href="anova-de-dos-factores.html#eficiencia"><i class="fa fa-check"></i><b>7.1.1</b> Eficiencia:</a></li>
</ul></li>
<li class="chapter" data-level="7.2" data-path="anova-de-dos-factores.html"><a href="anova-de-dos-factores.html#elementos-del-modelo"><i class="fa fa-check"></i><b>7.2</b> Elementos del Modelo</a><ul>
<li class="chapter" data-level="7.2.1" data-path="anova-de-dos-factores.html"><a href="anova-de-dos-factores.html#efectos-principales"><i class="fa fa-check"></i><b>7.2.1</b> Efectos principales</a></li>
</ul></li>
<li class="chapter" data-level="7.3" data-path="anova-de-dos-factores.html"><a href="anova-de-dos-factores.html#representacion-grafica"><i class="fa fa-check"></i><b>7.3</b> Representación gráfica</a></li>
<li class="chapter" data-level="7.4" data-path="anova-de-dos-factores.html"><a href="anova-de-dos-factores.html#interaccion"><i class="fa fa-check"></i><b>7.4</b> Interacción</a><ul>
<li class="chapter" data-level="7.4.1" data-path="anova-de-dos-factores.html"><a href="anova-de-dos-factores.html#interacciones-no-importantes"><i class="fa fa-check"></i><b>7.4.1</b> Interacciones no importantes</a></li>
</ul></li>
<li class="chapter" data-level="7.5" data-path="anova-de-dos-factores.html"><a href="anova-de-dos-factores.html#modelo-i-para-estudios-de-dos-factores"><i class="fa fa-check"></i><b>7.5</b> MODELO I PARA ESTUDIOS DE DOS FACTORES</a><ul>
<li class="chapter" data-level="7.5.1" data-path="anova-de-dos-factores.html"><a href="anova-de-dos-factores.html#modelo-de-las-medias-de-celdas"><i class="fa fa-check"></i><b>7.5.1</b> Modelo de las medias de celdas</a></li>
<li class="chapter" data-level="7.5.2" data-path="anova-de-dos-factores.html"><a href="anova-de-dos-factores.html#modelo-de-los-efectos-de-los-factores"><i class="fa fa-check"></i><b>7.5.2</b> Modelo de los efectos de los factores</a></li>
<li class="chapter" data-level="7.5.3" data-path="anova-de-dos-factores.html"><a href="anova-de-dos-factores.html#anova-modelo-i"><i class="fa fa-check"></i><b>7.5.3</b> ANOVA (MODELO I)</a></li>
</ul></li>
<li class="chapter" data-level="7.6" data-path="anova-de-dos-factores.html"><a href="anova-de-dos-factores.html#prueba-de-f"><i class="fa fa-check"></i><b>7.6</b> Prueba de F</a></li>
<li class="chapter" data-level="7.7" data-path="anova-de-dos-factores.html"><a href="anova-de-dos-factores.html#contrastes-1"><i class="fa fa-check"></i><b>7.7</b> Contrastes</a><ul>
<li class="chapter" data-level="7.7.1" data-path="anova-de-dos-factores.html"><a href="anova-de-dos-factores.html#entre-filas"><i class="fa fa-check"></i><b>7.7.1</b> Entre Filas</a></li>
<li class="chapter" data-level="7.7.2" data-path="anova-de-dos-factores.html"><a href="anova-de-dos-factores.html#entre-columnas"><i class="fa fa-check"></i><b>7.7.2</b> Entre columnas</a></li>
<li class="chapter" data-level="7.7.3" data-path="anova-de-dos-factores.html"><a href="anova-de-dos-factores.html#interaccion-1"><i class="fa fa-check"></i><b>7.7.3</b> Interacción</a></li>
</ul></li>
<li class="chapter" data-level="7.8" data-path="anova-de-dos-factores.html"><a href="anova-de-dos-factores.html#potencia-de-la-prueba-f-1"><i class="fa fa-check"></i><b>7.8</b> Potencia de la prueba F</a><ul>
<li class="chapter" data-level="7.8.1" data-path="anova-de-dos-factores.html"><a href="anova-de-dos-factores.html#interaccion-2"><i class="fa fa-check"></i><b>7.8.1</b> Interacción</a></li>
<li class="chapter" data-level="7.8.2" data-path="anova-de-dos-factores.html"><a href="anova-de-dos-factores.html#prueba-para-el-factor-principal-a"><i class="fa fa-check"></i><b>7.8.2</b> Prueba para el factor principal A:</a></li>
<li class="chapter" data-level="7.8.3" data-path="anova-de-dos-factores.html"><a href="anova-de-dos-factores.html#prueba-para-el-factor-principal-b"><i class="fa fa-check"></i><b>7.8.3</b> Prueba para el factor principal B:</a></li>
</ul></li>
<li class="chapter" data-level="7.9" data-path="anova-de-dos-factores.html"><a href="anova-de-dos-factores.html#caso-de-una-observacion-por-tratamiento"><i class="fa fa-check"></i><b>7.9</b> CASO DE UNA OBSERVACIÓN POR TRATAMIENTO</a><ul>
<li class="chapter" data-level="7.9.1" data-path="anova-de-dos-factores.html"><a href="anova-de-dos-factores.html#modelo-sin-interaccion"><i class="fa fa-check"></i><b>7.9.1</b> Modelo sin interacción</a></li>
<li class="chapter" data-level="7.9.2" data-path="anova-de-dos-factores.html"><a href="anova-de-dos-factores.html#prueba-de-tukey-aditividad"><i class="fa fa-check"></i><b>7.9.2</b> Prueba de Tukey (Aditividad)</a></li>
</ul></li>
<li class="chapter" data-level="7.10" data-path="anova-de-dos-factores.html"><a href="anova-de-dos-factores.html#modelo-ii-y-modelo-iii-para-estudios-de-dos-factores"><i class="fa fa-check"></i><b>7.10</b> MODELO II Y MODELO III PARA ESTUDIOS DE DOS FACTORES</a><ul>
<li class="chapter" data-level="7.10.1" data-path="anova-de-dos-factores.html"><a href="anova-de-dos-factores.html#modelo-aleatorio-modelo-ii"><i class="fa fa-check"></i><b>7.10.1</b> Modelo aleatorio (Modelo II)</a></li>
<li class="chapter" data-level="7.10.2" data-path="anova-de-dos-factores.html"><a href="anova-de-dos-factores.html#modelo-mixto-modelo-iii"><i class="fa fa-check"></i><b>7.10.2</b> Modelo Mixto (Modelo III)</a></li>
<li class="chapter" data-level="7.10.3" data-path="anova-de-dos-factores.html"><a href="anova-de-dos-factores.html#pruebas-estadisticas"><i class="fa fa-check"></i><b>7.10.3</b> Pruebas estadísticas</a></li>
<li class="chapter" data-level="7.10.4" data-path="anova-de-dos-factores.html"><a href="anova-de-dos-factores.html#estimacion-de-los-componentes-de-la-varianza"><i class="fa fa-check"></i><b>7.10.4</b> Estimación de los componentes de la varianza</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="8" data-path="problemas-anova-dos-factores.html"><a href="problemas-anova-dos-factores.html"><i class="fa fa-check"></i><b>8</b> Problemas ANOVA Dos Factores</a><ul>
<li class="chapter" data-level="8.1" data-path="problemas-anova-dos-factores.html"><a href="problemas-anova-dos-factores.html#formulas-con-mas-de-una-variable-independiente"><i class="fa fa-check"></i><b>8.1</b> Formulas con más de una variable independiente</a><ul>
<li class="chapter" data-level="8.1.1" data-path="problemas-anova-dos-factores.html"><a href="problemas-anova-dos-factores.html#test-de-aditividad-de-tukey-aditividad-tukey."><i class="fa fa-check"></i><b>8.1.1</b> Test de aditividad de Tukey {#aditividad-tukey}.</a></li>
</ul></li>
<li class="chapter" data-level="8.2" data-path="problemas-anova-dos-factores.html"><a href="problemas-anova-dos-factores.html#problemas-1"><i class="fa fa-check"></i><b>8.2</b> Problemas</a></li>
</ul></li>
<li class="chapter" data-level="9" data-path="prueba-de-wilcoxon-mann-whitney-para-dos-pruebas-independientes.html"><a href="prueba-de-wilcoxon-mann-whitney-para-dos-pruebas-independientes.html"><i class="fa fa-check"></i><b>9</b> Prueba de Wilcoxon-Mann-Whitney para dos pruebas independientes</a><ul>
<li class="chapter" data-level="9.1" data-path="prueba-de-wilcoxon-mann-whitney-para-dos-pruebas-independientes.html"><a href="prueba-de-wilcoxon-mann-whitney-para-dos-pruebas-independientes.html#datos"><i class="fa fa-check"></i><b>9.1</b> Datos</a></li>
<li class="chapter" data-level="9.2" data-path="prueba-de-wilcoxon-mann-whitney-para-dos-pruebas-independientes.html"><a href="prueba-de-wilcoxon-mann-whitney-para-dos-pruebas-independientes.html#supuestos"><i class="fa fa-check"></i><b>9.2</b> Supuestos</a></li>
<li class="chapter" data-level="9.3" data-path="prueba-de-wilcoxon-mann-whitney-para-dos-pruebas-independientes.html"><a href="prueba-de-wilcoxon-mann-whitney-para-dos-pruebas-independientes.html#np-algoritmo"><i class="fa fa-check"></i><b>9.3</b> Procedimiento básico</a><ul>
<li class="chapter" data-level="9.3.1" data-path="prueba-de-wilcoxon-mann-whitney-para-dos-pruebas-independientes.html"><a href="prueba-de-wilcoxon-mann-whitney-para-dos-pruebas-independientes.html#ejemplo"><i class="fa fa-check"></i><b>9.3.1</b> Ejemplo</a></li>
</ul></li>
<li class="chapter" data-level="9.4" data-path="prueba-de-wilcoxon-mann-whitney-para-dos-pruebas-independientes.html"><a href="prueba-de-wilcoxon-mann-whitney-para-dos-pruebas-independientes.html#estadisticos"><i class="fa fa-check"></i><b>9.4</b> Estadísticos</a><ul>
<li class="chapter" data-level="9.4.1" data-path="prueba-de-wilcoxon-mann-whitney-para-dos-pruebas-independientes.html"><a href="prueba-de-wilcoxon-mann-whitney-para-dos-pruebas-independientes.html#variante-wilcoxon-w"><i class="fa fa-check"></i><b>9.4.1</b> Variante Wilcoxon (W)</a></li>
<li class="chapter" data-level="9.4.2" data-path="prueba-de-wilcoxon-mann-whitney-para-dos-pruebas-independientes.html"><a href="prueba-de-wilcoxon-mann-whitney-para-dos-pruebas-independientes.html#variante-mann-whitney-u"><i class="fa fa-check"></i><b>9.4.2</b> Variante Mann-Whitney (U)</a></li>
</ul></li>
<li class="chapter" data-level="9.5" data-path="prueba-de-wilcoxon-mann-whitney-para-dos-pruebas-independientes.html"><a href="prueba-de-wilcoxon-mann-whitney-para-dos-pruebas-independientes.html#hipotesis"><i class="fa fa-check"></i><b>9.5</b> Hipótesis</a><ul>
<li class="chapter" data-level="9.5.1" data-path="prueba-de-wilcoxon-mann-whitney-para-dos-pruebas-independientes.html"><a href="prueba-de-wilcoxon-mann-whitney-para-dos-pruebas-independientes.html#prueba-a-dos-colas"><i class="fa fa-check"></i><b>9.5.1</b> Prueba a dos colas</a></li>
<li class="chapter" data-level="9.5.2" data-path="prueba-de-wilcoxon-mann-whitney-para-dos-pruebas-independientes.html"><a href="prueba-de-wilcoxon-mann-whitney-para-dos-pruebas-independientes.html#prueba-de-una-cola-a-la-izquierda"><i class="fa fa-check"></i><b>9.5.2</b> Prueba de una cola a la izquierda</a></li>
<li class="chapter" data-level="9.5.3" data-path="prueba-de-wilcoxon-mann-whitney-para-dos-pruebas-independientes.html"><a href="prueba-de-wilcoxon-mann-whitney-para-dos-pruebas-independientes.html#prueba-de-una-cola-a-la-derecha"><i class="fa fa-check"></i><b>9.5.3</b> Prueba de una cola a la derecha</a></li>
</ul></li>
<li class="chapter" data-level="9.6" data-path="prueba-de-wilcoxon-mann-whitney-para-dos-pruebas-independientes.html"><a href="prueba-de-wilcoxon-mann-whitney-para-dos-pruebas-independientes.html#ejemplo-2"><i class="fa fa-check"></i><b>9.6</b> Ejemplo 2</a></li>
<li class="chapter" data-level="9.7" data-path="prueba-de-wilcoxon-mann-whitney-para-dos-pruebas-independientes.html"><a href="prueba-de-wilcoxon-mann-whitney-para-dos-pruebas-independientes.html#prueba-de-wilcoxon-de-rangos-con-signo-para-muestras-apareadas"><i class="fa fa-check"></i><b>9.7</b> Prueba de Wilcoxon de rangos con signo para muestras apareadas</a><ul>
<li class="chapter" data-level="9.7.1" data-path="prueba-de-wilcoxon-mann-whitney-para-dos-pruebas-independientes.html"><a href="prueba-de-wilcoxon-mann-whitney-para-dos-pruebas-independientes.html#supuestos-1"><i class="fa fa-check"></i><b>9.7.1</b> Supuestos</a></li>
<li class="chapter" data-level="9.7.2" data-path="prueba-de-wilcoxon-mann-whitney-para-dos-pruebas-independientes.html"><a href="prueba-de-wilcoxon-mann-whitney-para-dos-pruebas-independientes.html#estadisticos-1"><i class="fa fa-check"></i><b>9.7.2</b> Estadísticos</a></li>
<li class="chapter" data-level="9.7.3" data-path="prueba-de-wilcoxon-mann-whitney-para-dos-pruebas-independientes.html"><a href="prueba-de-wilcoxon-mann-whitney-para-dos-pruebas-independientes.html#hipotesis-1"><i class="fa fa-check"></i><b>9.7.3</b> Hipótesis</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="10" data-path="ejercicios-de-dos-muestras-no-parametrico.html"><a href="ejercicios-de-dos-muestras-no-parametrico.html"><i class="fa fa-check"></i><b>10</b> Ejercicios de dos muestras no paramétrico</a><ul>
<li class="chapter" data-level="10.1" data-path="ejercicios-de-dos-muestras-no-parametrico.html"><a href="ejercicios-de-dos-muestras-no-parametrico.html#reproduciendo-el-algoritmo-manualmente"><i class="fa fa-check"></i><b>10.1</b> Reproduciendo el algoritmo manualmente</a></li>
<li class="chapter" data-level="10.2" data-path="ejercicios-de-dos-muestras-no-parametrico.html"><a href="ejercicios-de-dos-muestras-no-parametrico.html#funciones-no-parametricas-en-r"><i class="fa fa-check"></i><b>10.2</b> Funciones no paramétricas en <em>R</em></a></li>
<li class="chapter" data-level="10.3" data-path="ejercicios-de-dos-muestras-no-parametrico.html"><a href="ejercicios-de-dos-muestras-no-parametrico.html#formulas"><i class="fa fa-check"></i><b>10.3</b> Fórmulas</a></li>
<li class="chapter" data-level="10.4" data-path="ejercicios-de-dos-muestras-no-parametrico.html"><a href="ejercicios-de-dos-muestras-no-parametrico.html#muestras-apareadas"><i class="fa fa-check"></i><b>10.4</b> Muestras apareadas</a></li>
<li class="chapter" data-level="10.5" data-path="ejercicios-de-dos-muestras-no-parametrico.html"><a href="ejercicios-de-dos-muestras-no-parametrico.html#problemas-2"><i class="fa fa-check"></i><b>10.5</b> Problemas</a></li>
</ul></li>
<li class="chapter" data-level="11" data-path="anova-no-parametrico.html"><a href="anova-no-parametrico.html"><i class="fa fa-check"></i><b>11</b> ANOVA No Paramétrico</a><ul>
<li class="chapter" data-level="11.1" data-path="anova-no-parametrico.html"><a href="anova-no-parametrico.html#pruebas-para-varias-muestras-independientes"><i class="fa fa-check"></i><b>11.1</b> Pruebas para varias muestras independientes</a><ul>
<li class="chapter" data-level="11.1.1" data-path="anova-no-parametrico.html"><a href="anova-no-parametrico.html#prueba-de-la-mediana"><i class="fa fa-check"></i><b>11.1.1</b> Prueba de la mediana</a></li>
</ul></li>
<li class="chapter" data-level="11.2" data-path="anova-no-parametrico.html"><a href="anova-no-parametrico.html#prueba-de-kruskal-wallis"><i class="fa fa-check"></i><b>11.2</b> Prueba de Kruskal-Wallis</a><ul>
<li class="chapter" data-level="11.2.1" data-path="anova-no-parametrico.html"><a href="anova-no-parametrico.html#datos-2"><i class="fa fa-check"></i><b>11.2.1</b> Datos</a></li>
<li class="chapter" data-level="11.2.2" data-path="anova-no-parametrico.html"><a href="anova-no-parametrico.html#supuestos-3"><i class="fa fa-check"></i><b>11.2.2</b> Supuestos</a></li>
<li class="chapter" data-level="11.2.3" data-path="anova-no-parametrico.html"><a href="anova-no-parametrico.html#procedimiento-1"><i class="fa fa-check"></i><b>11.2.3</b> Procedimiento</a></li>
<li class="chapter" data-level="11.2.4" data-path="anova-no-parametrico.html"><a href="anova-no-parametrico.html#hipotesis-3"><i class="fa fa-check"></i><b>11.2.4</b> Hipótesis</a></li>
<li class="chapter" data-level="11.2.5" data-path="anova-no-parametrico.html"><a href="anova-no-parametrico.html#contrastes-3"><i class="fa fa-check"></i><b>11.2.5</b> Contrastes</a></li>
<li class="chapter" data-level="11.2.6" data-path="anova-no-parametrico.html"><a href="anova-no-parametrico.html#comentarios-3"><i class="fa fa-check"></i><b>11.2.6</b> Comentarios</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="12" data-path="problemas-de-anova-no-parametrico.html"><a href="problemas-de-anova-no-parametrico.html"><i class="fa fa-check"></i><b>12</b> Problemas de ANOVA No Paramétrico</a><ul>
<li class="chapter" data-level="12.1" data-path="problemas-de-anova-no-parametrico.html"><a href="problemas-de-anova-no-parametrico.html#problemas-3"><i class="fa fa-check"></i><b>12.1</b> Problemas</a></li>
</ul></li>
<li class="chapter" data-level="13" data-path="disenos-experimentales.html"><a href="disenos-experimentales.html"><i class="fa fa-check"></i><b>13</b> DISEÑOS EXPERIMENTALES</a><ul>
<li class="chapter" data-level="13.1" data-path="disenos-experimentales.html"><a href="disenos-experimentales.html#bloques-al-azar"><i class="fa fa-check"></i><b>13.1</b> Bloques al azar</a><ul>
<li class="chapter" data-level="13.1.1" data-path="disenos-experimentales.html"><a href="disenos-experimentales.html#diseno-de-experimentos"><i class="fa fa-check"></i><b>13.1.1</b> Diseño de experimentos</a></li>
<li class="chapter" data-level="13.1.2" data-path="disenos-experimentales.html"><a href="disenos-experimentales.html#elementos-de-los-disenos-de-bloques-al-azar"><i class="fa fa-check"></i><b>13.1.2</b> Elementos de los Diseños de Bloques al Azar</a></li>
<li class="chapter" data-level="13.1.3" data-path="disenos-experimentales.html"><a href="disenos-experimentales.html#criterios-para-definir-los-bloques"><i class="fa fa-check"></i><b>13.1.3</b> Criterios para definir los bloques</a></li>
<li class="chapter" data-level="13.1.4" data-path="disenos-experimentales.html"><a href="disenos-experimentales.html#ventajas-y-desventajas"><i class="fa fa-check"></i><b>13.1.4</b> Ventajas y desventajas</a></li>
<li class="chapter" data-level="13.1.5" data-path="disenos-experimentales.html"><a href="disenos-experimentales.html#modelo"><i class="fa fa-check"></i><b>13.1.5</b> Modelo</a></li>
</ul></li>
<li class="chapter" data-level="13.2" data-path="disenos-experimentales.html"><a href="disenos-experimentales.html#analisis-de-la-varianza-y-pruebas"><i class="fa fa-check"></i><b>13.2</b> Análisis de la varianza y pruebas</a><ul>
<li class="chapter" data-level="13.2.1" data-path="disenos-experimentales.html"><a href="disenos-experimentales.html#analisis-de-la-varianza"><i class="fa fa-check"></i><b>13.2.1</b> Análisis de la varianza</a></li>
<li class="chapter" data-level="13.2.2" data-path="disenos-experimentales.html"><a href="disenos-experimentales.html#prueba-de-tukey-de-aditividad"><i class="fa fa-check"></i><b>13.2.2</b> Prueba de Tukey de Aditividad</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="14" data-path="problemas-anova-diseno-experimental.html"><a href="problemas-anova-diseno-experimental.html"><i class="fa fa-check"></i><b>14</b> Problemas ANOVA Diseño Experimental</a><ul>
<li class="chapter" data-level="14.1" data-path="problemas-anova-diseno-experimental.html"><a href="problemas-anova-diseno-experimental.html#ejemplo-1"><i class="fa fa-check"></i><b>14.1</b> Ejemplo</a></li>
<li class="chapter" data-level="14.2" data-path="problemas-anova-diseno-experimental.html"><a href="problemas-anova-diseno-experimental.html#problemas-4"><i class="fa fa-check"></i><b>14.2</b> Problemas</a></li>
</ul></li>
<li class="chapter" data-level="15" data-path="pruebas-para-varias-muestras-pareadas.html"><a href="pruebas-para-varias-muestras-pareadas.html"><i class="fa fa-check"></i><b>15</b> Pruebas para varias muestras pareadas</a><ul>
<li class="chapter" data-level="15.1" data-path="pruebas-para-varias-muestras-pareadas.html"><a href="pruebas-para-varias-muestras-pareadas.html#prueba-de-friedman-para-varias-muestras-relacionadas"><i class="fa fa-check"></i><b>15.1</b> Prueba de Friedman para varias muestras relacionadas</a><ul>
<li class="chapter" data-level="15.1.1" data-path="pruebas-para-varias-muestras-pareadas.html"><a href="pruebas-para-varias-muestras-pareadas.html#estadistico"><i class="fa fa-check"></i><b>15.1.1</b> Estadístico</a></li>
<li class="chapter" data-level="15.1.2" data-path="pruebas-para-varias-muestras-pareadas.html"><a href="pruebas-para-varias-muestras-pareadas.html#supuestos-4"><i class="fa fa-check"></i><b>15.1.2</b> Supuestos</a></li>
<li class="chapter" data-level="15.1.3" data-path="pruebas-para-varias-muestras-pareadas.html"><a href="pruebas-para-varias-muestras-pareadas.html#hipotesis-5"><i class="fa fa-check"></i><b>15.1.3</b> Hipótesis</a></li>
<li class="chapter" data-level="15.1.4" data-path="pruebas-para-varias-muestras-pareadas.html"><a href="pruebas-para-varias-muestras-pareadas.html#comparaciones-multiples-1"><i class="fa fa-check"></i><b>15.1.4</b> Comparaciones múltiples</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="16" data-path="practico-de-pruebas-no-parametricas-para-muestras-relacionadas.html"><a href="practico-de-pruebas-no-parametricas-para-muestras-relacionadas.html"><i class="fa fa-check"></i><b>16</b> Práctico de Pruebas no paramétricas para muestras relacionadas</a><ul>
<li class="chapter" data-level="16.1" data-path="practico-de-pruebas-no-parametricas-para-muestras-relacionadas.html"><a href="practico-de-pruebas-no-parametricas-para-muestras-relacionadas.html#problemas-5"><i class="fa fa-check"></i><b>16.1</b> Problemas</a></li>
<li class="chapter" data-level="16.2" data-path="practico-de-pruebas-no-parametricas-para-muestras-relacionadas.html"><a href="practico-de-pruebas-no-parametricas-para-muestras-relacionadas.html#problema-4"><i class="fa fa-check"></i><b>16.2</b> Problema 4</a></li>
</ul></li>
<li class="chapter" data-level="17" data-path="regresion.html"><a href="regresion.html"><i class="fa fa-check"></i><b>17</b> Regresión</a><ul>
<li class="chapter" data-level="17.1" data-path="regresion.html"><a href="regresion.html#regresion-lineal-simple"><i class="fa fa-check"></i><b>17.1</b> Regresión Lineal Simple</a><ul>
<li class="chapter" data-level="17.1.1" data-path="regresion.html"><a href="regresion.html#intervalos-de-confianza"><i class="fa fa-check"></i><b>17.1.1</b> Intervalos de confianza</a></li>
</ul></li>
<li class="chapter" data-level="17.2" data-path="regresion.html"><a href="regresion.html#regresion-con-replicacion"><i class="fa fa-check"></i><b>17.2</b> Regresión con Replicación</a></li>
<li class="chapter" data-level="17.3" data-path="regresion.html"><a href="regresion.html#transformaciones-para-corregir-la-falta-de-linealidad"><i class="fa fa-check"></i><b>17.3</b> Transformaciones para corregir la falta de linealidad</a></li>
<li class="chapter" data-level="17.4" data-path="regresion.html"><a href="regresion.html#uso-de-los-residuales-para-comprobar-los-supuestos"><i class="fa fa-check"></i><b>17.4</b> Uso de los Residuales para Comprobar los Supuestos</a></li>
<li class="chapter" data-level="17.5" data-path="regresion.html"><a href="regresion.html#regresiones-multiples"><i class="fa fa-check"></i><b>17.5</b> Regresiones Múltiples</a></li>
</ul></li>
<li class="chapter" data-level="18" data-path="ordenacion-en-espacios-reducidos.html"><a href="ordenacion-en-espacios-reducidos.html"><i class="fa fa-check"></i><b>18</b> Ordenación en Espacios Reducidos</a><ul>
<li class="chapter" data-level="18.1" data-path="ordenacion-en-espacios-reducidos.html"><a href="ordenacion-en-espacios-reducidos.html#analisis-de-componentes-principales"><i class="fa fa-check"></i><b>18.1</b> Análisis de componentes principales</a><ul>
<li class="chapter" data-level="18.1.1" data-path="ordenacion-en-espacios-reducidos.html"><a href="ordenacion-en-espacios-reducidos.html#biplots"><i class="fa fa-check"></i><b>18.1.1</b> Biplots</a></li>
</ul></li>
<li class="chapter" data-level="18.2" data-path="ordenacion-en-espacios-reducidos.html"><a href="ordenacion-en-espacios-reducidos.html#componentes-principales-de-una-matriz-de-correlacion"><i class="fa fa-check"></i><b>18.2</b> Componentes principales de una matriz de correlación</a></li>
<li class="chapter" data-level="18.3" data-path="ordenacion-en-espacios-reducidos.html"><a href="ordenacion-en-espacios-reducidos.html#cuantos-componentes-son-significativos"><i class="fa fa-check"></i><b>18.3</b> ¿Cuantos componentes son significativos?</a></li>
<li class="chapter" data-level="18.4" data-path="ordenacion-en-espacios-reducidos.html"><a href="ordenacion-en-espacios-reducidos.html#mal-uso-de-los-componentes-principales"><i class="fa fa-check"></i><b>18.4</b> Mal uso de los componentes principales</a></li>
</ul></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Estadística Avanzada para Ciencias Naturales</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="regresion" class="section level1">
<h1><span class="header-section-number">Capítulo 17</span> Regresión</h1>
<p>En las ciencias naturales es usual querer explicar una variable con otras.
Las variables que se quieren explicar son las variables dependientes y las
que se usan para explicar son las llamadas variables explicatorias o también
independientes. A estos modelos se los conoce como modelos de regresión. Aunque
las variables estén relacionadas esto no implica que haya una relación causal
entre ellas. Sin un modelo causal que explique la manera que las variables
se relación se está incurriendo una falacia del tipo <em>cum hoc ergo propter
hoc</em>. Por ejemplo, en la Figura <a href="regresion.html#fig:regresion-espuria">17.1</a> se muestra que
la relación entre los limones frescos importados desde México (ton) y tasa de
mortalidad total en autopistas de EE.UU. Según esta regresión al ¡aumentar la
importación de disminuye la tasa de mortalidad! Este resultado carece de lógica
ya que no hay una forma en que la importación de limones afecte la mortalidad.
Por este motivo hay que ser cuidadoso en cuanto a las conclusiones que se
realizan con los resultados.</p>
<p>(ref:regresion-espuria) Ejemplo de regresión espuria. Limones frescos importados
desde México (ton) y tasa de mortalidad total en autopistas de EE.UU.</p>
<div class="figure"><span id="fig:regresion-espuria"></span>
<img src="fig/regresion-espuria.png" alt="(ref:regresion-espuria)" width="6" />
<p class="caption">
Figura 17.1: (ref:regresion-espuria)
</p>
</div>
<div id="regresion-lineal-simple" class="section level2">
<h2><span class="header-section-number">17.1</span> Regresión Lineal Simple</h2>
<p>La regresión lineal simple se da cuando hay una variable aleatoria con
distribución normal y solo una variable predictora. La varible predictora no
es una variable aleatoria, sino que puede ser modificada por el investigador.
El objetivo de esta técnica es obtener una ecuación lineal que explique
el cambio de la variable aleatoria según el cambio de la variable predictora:</p>
<span class="math display" id="eq:reg1">\[\begin{equation}
Y_i = \beta_0 + \beta_1 X_i
\tag{17.1}
\end{equation}\]</span>
<p>Por ejemplo, el se tiene la edad y la longitud de alas de gorriones de varias
edades en la Tabla <a href="#tab:gorriones"><strong>??</strong></a>. La edad es la variable independiente y
la longitud de ala es la variable dependiente. Se busca ajustar un modelo como
en el da la Ecuación <a href="regresion.html#eq:reg1">(17.1)</a>. En la Figura <a href="regresion.html#fig:gorriones-grafico">17.2</a> la
recta que mejor ajusta a esto datos en azul. Sin embargo, el ajuste no es
perfecto. La diferencia entre el valor ajustado o predicho y el valor observado
es el error que se comete. Ese error se simboliza con la letra griega epsilon y
debe ser incluido en el modelo:</p>
<span class="math display" id="eq:reg2">\[\begin{equation}
Y_i = \beta_0 + \beta_1 X_i + \epsilon_i
\tag{17.2}
\end{equation}\]</span>
<p>Se asume que <span class="math inline">\(\epsilon_i\sim N\left ( 0, \sigma^2 \right )\)</span> y por lo tanto
<span class="math inline">\(\sum \epsilon_i = 0\)</span>. El método que se usa para encontrar los estimadores de
los <span class="math inline">\(\beta_i\)</span> consiste en minimizar el cuadrado de los errores. Por eso,
el método se lo conoce como mínimos cuadrados o mínimos cuadrados ordinarios.
Afortunadamente se pueden resolver de manera analítica por las siguientes
ecuaciones:</p>
<span class="math display" id="eq:betas">\[\begin{equation}
\begin{aligned}
b_1 &amp;= \frac{\sum(X_i-\overline{X})(Y_i-\overline{Y})}{\sum (X_i-\overline{X})^{2}}=\frac{\sum X_iY_i-\frac{\left (\sum X_i\right)\left ( \sum Y_i\right )}{n}}{\sum X_i^2-\frac{\left (\sum X_i \right )^2}{n}}\\
b_0 &amp;= \overline{Y} - b_1\overline{X}
\end{aligned}
\tag{17.3}
\end{equation}\]</span>
<p>Para facilitar las formulas y hacerlas más compactas definimos:</p>
<span class="math display">\[\begin{equation}
\begin{aligned}
\sum y^2 &amp;= \sum \left (Y_i - \overline{Y} \right )^2\\
\sum x^2 &amp;= \sum \left (X_i - \overline{X} \right )^2\\
\sum xy &amp;= \sum \left (X_i - \overline{X} \right )\left (Y_i - \overline{Y} \right )
\end{aligned}
\end{equation}\]</span>
<table>
<caption><span id="tab:gorriones-datos">Tabla 17.1: </span>Edad en días y longitud
de ala en centímetros de 13 gorriones.</caption>
<thead>
<tr class="header">
<th align="center">Edad</th>
<th align="center">Longitud</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="center">3</td>
<td align="center">1.4</td>
</tr>
<tr class="even">
<td align="center">4</td>
<td align="center">1.5</td>
</tr>
<tr class="odd">
<td align="center">5</td>
<td align="center">2.2</td>
</tr>
<tr class="even">
<td align="center">6</td>
<td align="center">2.4</td>
</tr>
<tr class="odd">
<td align="center">8</td>
<td align="center">3.1</td>
</tr>
<tr class="even">
<td align="center">9</td>
<td align="center">3.2</td>
</tr>
<tr class="odd">
<td align="center">10</td>
<td align="center">3.2</td>
</tr>
<tr class="even">
<td align="center">11</td>
<td align="center">3.9</td>
</tr>
<tr class="odd">
<td align="center">12</td>
<td align="center">4.1</td>
</tr>
<tr class="even">
<td align="center">14</td>
<td align="center">4.7</td>
</tr>
<tr class="odd">
<td align="center">15</td>
<td align="center">4.5</td>
</tr>
<tr class="even">
<td align="center">16</td>
<td align="center">5.2</td>
</tr>
<tr class="odd">
<td align="center">17</td>
<td align="center">5.0</td>
</tr>
</tbody>
</table>
<p>(ref:gorriones-grafico) Gráfico de dispersión de edad en días y longitud
de ala en centímetros de 13 gorriones. En azul línea de
regresión estimada con mínimos cuadrados ordinarios. En rojo
el error cometido por la regresión entre los valores estimados
y los valores observados.</p>
<div class="figure"><span id="fig:gorriones-grafico"></span>
<img src="regresion_files/figure-html/gorriones-grafico-1.png" alt="(ref:gorriones-grafico)" width="672" />
<p class="caption">
Figura 17.2: (ref:gorriones-grafico)
</p>
</div>
<p>Una vez que están determinados los <span class="math inline">\(\beta_i\)</span> es necesario determinar si son
signficativos. Es decir, diferentes de cero. El <span class="math inline">\(\beta_1\)</span> puede ser muy grande
(e.g. 100) pero si la varianza asociada a este número es muy grande puede que
no sea significativamente distinto de cero. Existen dos estadísticos que
permiten probar la significancia de <span class="math inline">\(\beta_1\)</span>.</p>
<p>El primero es un estadístico F que se calcula a partir de una tabla de análisis
de la varianza (ANOVA):</p>
<p><span class="math display">\[
F = \frac{CM_{regresion}}{CM_{residual}}
\]</span></p>
<table>
<thead>
<tr class="header">
<th align="left">Fuente de Variación</th>
<th align="left">GL</th>
<th align="left">Suma de Cuadrados (SC)</th>
<th align="left">Cuadrados Medios (CM)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">Regresión</td>
<td align="left"><span class="math inline">\(1\)</span></td>
<td align="left"><span class="math inline">\(\frac{\left (\sum xy \right )^2}{\sum x^2}\)</span></td>
<td align="left"><span class="math inline">\(\frac{SC_{regresion}}{GL_{regresion}}\)</span></td>
</tr>
<tr class="even">
<td align="left">Residual</td>
<td align="left"><span class="math inline">\(n-2\)</span></td>
<td align="left"><span class="math inline">\(SC_{total}-SC_{regresion}\)</span></td>
<td align="left"><span class="math inline">\(\frac{SC_{residual}}{GL_{residual}}\)</span></td>
</tr>
<tr class="odd">
<td align="left">Total</td>
<td align="left"><span class="math inline">\(n-1\)</span></td>
<td align="left"><span class="math inline">\(\sum y^2\)</span></td>
<td align="left"></td>
</tr>
</tbody>
</table>
<p>Este estadístico <em>F</em> bajo la hipótesis nula <span class="math inline">\(H_0: \beta_1 = 0\)</span> se distribuye
como <span class="math inline">\(F_{1;n-2}\)</span>. Entonces se compara con esa distribución y si el estadístico
es mayor que el valor crítico al <span class="math inline">\(\alpha\)</span> especificado o si la probabilidad es
de un valor mayor a estadístico es menor a <span class="math inline">\(\alpha\)</span> entonces se rechaza <span class="math inline">\(H_0\)</span>.</p>
<p>Por ejemplo, con los datos de la tabla <a href="regresion.html#tab:gorriones-datos">17.1</a>:</p>
<table>
<thead>
<tr class="header">
<th align="left">Fuente de Variación</th>
<th align="right">GL</th>
<th align="right">Suma de Cuadrados (SC)</th>
<th align="right">Cuadrados Medios (CM)</th>
<th align="right">F</th>
<th align="right">P(&gt;F)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">Regresión</td>
<td align="right">1</td>
<td align="right">19.1322137</td>
<td align="right">19.1322137</td>
<td align="right">401.0875</td>
<td align="right">0</td>
</tr>
<tr class="even">
<td align="left">Residual</td>
<td align="right">11</td>
<td align="right">0.5247093</td>
<td align="right">0.0477008</td>
<td align="right"></td>
<td align="right"></td>
</tr>
<tr class="odd">
<td align="left">Total</td>
<td align="right">12</td>
<td align="right">19.6569231</td>
<td align="right"></td>
<td align="right"></td>
<td align="right"></td>
</tr>
</tbody>
</table>
<p>La otra forma de hacer esta prueba es usando el estadístico <em>t</em>:</p>
<p><span class="math display" id="eq:test-beta">\[
t = \frac{b_1 - \beta_1}{s_{b1}}
\tag{17.4}
\]</span></p>
<p>En el caso de <span class="math inline">\(H_0: \beta_1 = 0\)</span> es claro que ese el valor que debe tomar
<span class="math inline">\(\beta_1\)</span> en la Ecuación <a href="regresion.html#eq:test-beta">(17.4)</a>. Por otro lado, esta forma de
probar la significancia del estimador <span class="math inline">\(b_1\)</span> tiene la ventaja de poder probar
a una cola izquierda o derecha y con distintos valores de <span class="math inline">\(\beta_1\)</span> (e.g. 1, 3.
100, etc.).</p>
<p>La varianza de <span class="math inline">\(b_1\)</span> se calcula como:</p>
<p><span class="math display">\[
s_b^2=\frac{s^2_{YX}}{\sum x^2}
\]</span></p>
<p>Donde el estimador de <span class="math inline">\(s^2_{YX}\)</span> es el <span class="math inline">\(CM_{residual}\)</span> en la tabla de anovo.</p>
<p>El coeficiente de determinación <span class="math inline">\(r^2\)</span> es igual a la proporción de la varianza
de Y explicada por la regresion:</p>
<p><span class="math display">\[
r^2 = \frac{SC_{regresion}}{SC{total}}
\]</span></p>
<p>La interpretación de la función de regresión es que <span class="math inline">\(\beta_0\)</span> es el valor que toma
<span class="math inline">\(Y\)</span> cuando <span class="math inline">\(X=0\)</span>. No siempre tiene sentido biológico este parámetro.
Por ejemplo, si la variable <span class="math inline">\(X\)</span> es el peso de un animal, <strong>¡no existe un animal
con peso 0!</strong>. Por otro lado, en el caso de los gorriones este valor representa
la longitud media del ala de un gorrión al nacer.</p>
<p>La interpretación de <span class="math inline">\(\beta_1\)</span> es cuanto aumenta (o disminuye) <span class="math inline">\(Y\)</span> por cada
unidad de <span class="math inline">\(X\)</span>.</p>
<div id="intervalos-de-confianza" class="section level3">
<h3><span class="header-section-number">17.1.1</span> Intervalos de confianza</h3>
<p>El intervalo de confianza para <span class="math inline">\(b_1\)</span> es:</p>
<p><span class="math display">\[
b_1 \pm t_{\alpha(2);n-2} s_b
\]</span></p>
<p>El intervalo de confianza para cada <span class="math inline">\(Y\)</span> es distinto que el de para
una media. Debido a que la pendiente <span class="math inline">\(b_1\)</span> tiene varianza hace que los
intervalos de confianza de <span class="math inline">\(Y\)</span> sean mayores en los extremos que en el centro.
Podemos imaginarlo como un subibaja donde el punto donde está sostenido es
igual a <span class="math inline">\(\overline{X}\)</span>. Por lo tanto la varianza de <span class="math inline">\(\hat{Y}\)</span> aumenta a medida
que se aleja de <span class="math inline">\(\overline{X}\)</span></p>
<p><span class="math display">\[
S_{\hat{Y}}= \sqrt{S^2_{YX}\left[ \frac{1}{n} + \frac{\left( X_i - \overline{X} \right)^2}{\sum x^2} \right ]}
\]</span>
Luego se construye normalmente como cualquier otro intervalo de confianza:</p>
<p><span class="math display">\[
\hat Y \pm t_{\alpha(2);n-2}S_{\hat Y}
\]</span></p>
<p>En cambio, el intervalo de predicción para un nuevo <span class="math inline">\(Y\)</span> depende de la cantidad de
nuevas estimaciones que se quieran predecir:</p>
<p><span class="math display">\[
(S_{\hat{Y}})_m= \sqrt{S^2_{YX}\left[\frac{1}{m} + \frac{1}{n} + \frac{\left( X_i - \overline{X} \right)^2}{\sum x^2} \right ]}
\]</span></p>
<p>Donde <span class="math inline">\(m\)</span> es el número de nuevas predicciones en en un mismo <span class="math inline">\(X_i\)</span>.</p>
</div>
</div>
<div id="regresion-con-replicacion" class="section level2">
<h2><span class="header-section-number">17.2</span> Regresión con Replicación</h2>
<p>La regresión lineal simple vista anteriormente es para cuando solo hay una
observación por cada <span class="math inline">\(X_i\)</span>. Cuando tenemos varias observaciones por cada
<span class="math inline">\(X_i\)</span> es posible probar la hipótesis sobre la linealidad de los datos.
Esto es posible de probar porque cada observación proviene de una distribución
normal con media <span class="math inline">\(\beta_0 + \beta_1X\)</span>. Por lo tanto, la media de las réplicas
de cada <span class="math inline">\(X_i\)</span> debería coincidir con el valor de <span class="math inline">\(\hat{Y}\)</span> de la regresión.
Por ejemplo, se tienen mediciones de la presión sistólica de hombres de diferentes
edades, con varias mediciones para la misma edad en la Tabla @ref(tab:presión-sistolica).
En la Figura <a href="#fig:grafico-sistolica"><strong>??</strong></a> se graficaron estos datos. Además,
se añadió la recta de regresión estimada.</p>
<table>
<caption><span id="tab:presión-sistolica">Tabla 17.2: </span>Presión sistólica (mm Hg) en hombres de varias edades.</caption>
<thead>
<tr class="header">
<th align="right">edad</th>
<th align="left">presion</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="right">30</td>
<td align="left">108, 110, 106</td>
</tr>
<tr class="even">
<td align="right">40</td>
<td align="left">125, 120, 118, 119</td>
</tr>
<tr class="odd">
<td align="right">50</td>
<td align="left">132, 137, 134</td>
</tr>
<tr class="even">
<td align="right">60</td>
<td align="left">148, 151, 146, 147, 144</td>
</tr>
<tr class="odd">
<td align="right">70</td>
<td align="left">162, 156, 164, 158, 159</td>
</tr>
</tbody>
</table>
<p><img src="regresion_files/figure-html/grafico-sistotlica-1.png" width="672" /></p>
<p>Entonces, si tenemos réplicas por cada X es posible estimar las desviaciones de
la linealidad. La hipótesis nula es que la población es linear vs la alternativa
que no es linear:</p>
<p><span class="math display">\[ 
H_0 : \text{la población es linear}\\
H_a: \text{la población no es linear}
\]</span></p>
<p>La forma de poner a prueba esta hipótesis es mediante un estadístico F.</p>
<p><span class="math display">\[
F = \frac{CM_{desviaciones}}{CM_{dentro}}
\]</span></p>
<p>La varianza total puede ser divididad entre la varianza residual o dentro de
los grupos, y la varianza entre los grupos que además puede ser divida entre la
que explicada por la regresión linear y la que no explicada por la regresión
linear que se asume que es debida a desviaciones de la linealidad.</p>
<table>
<thead>
<tr class="header">
<th align="left">Fuente de Variación</th>
<th align="left">GL</th>
<th align="left">Suma de Cuadrados (SC)</th>
<th align="left">Cuadrados Medios (CM)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">Entre grupos</td>
<td align="left"><span class="math inline">\(I - 1\)</span></td>
<td align="left"><span class="math inline">\(\sum\frac{\left(\sum Y_ij\right)^2}{n_i} - \frac{\left (\sum\sum Y_ij\right )}{N}\)</span></td>
<td align="left"></td>
</tr>
<tr class="even">
<td align="left">Regresión Lineal</td>
<td align="left"><span class="math inline">\(1\)</span></td>
<td align="left"><span class="math inline">\(\frac{\left (\sum xy \right )^2}{\sum x^2}\)</span></td>
<td align="left"></td>
</tr>
<tr class="odd">
<td align="left">Desviaciones de la linealidad</td>
<td align="left"><span class="math inline">\(I - 2\)</span></td>
<td align="left"><span class="math inline">\(SC_{entre} - SC{regresion}\)</span></td>
<td align="left"><span class="math inline">\(\frac{SC_{desviaciones}}{GL_{desviaciones}}\)</span></td>
</tr>
<tr class="even">
<td align="left">Dentro de grupos</td>
<td align="left">$N - I $</td>
<td align="left"><span class="math inline">\(SC_{total}-SC_{entre}\)</span></td>
<td align="left"><span class="math inline">\(\frac{SC_{dentro}}{GL_{dentro}}\)</span></td>
</tr>
<tr class="odd">
<td align="left">Total</td>
<td align="left"><span class="math inline">\(N-1\)</span></td>
<td align="left"><span class="math inline">\(\sum y^2\)</span></td>
<td align="left"></td>
</tr>
</tbody>
</table>
<p>El estadístico F sigue una distribución F con I - 2 grados de libertad en el
numerador y N-I en el denominador si <span class="math inline">\(H_0\)</span> es cierta.</p>
<table>
<thead>
<tr class="header">
<th align="left">Fuente de Variación</th>
<th align="left">GL</th>
<th align="left">Suma de Cuadrados (SC)</th>
<th align="left">Cuadrados Medios (CM)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">Entre grupos</td>
<td align="left"><span class="math inline">\(4\)</span></td>
<td align="left"><span class="math inline">\(6751.93\)</span></td>
<td align="left"></td>
</tr>
<tr class="even">
<td align="left">Regresión Lineal</td>
<td align="left"><span class="math inline">\(1\)</span></td>
<td align="left"><span class="math inline">\(6750.29\)</span></td>
<td align="left"></td>
</tr>
<tr class="odd">
<td align="left">Desviaciones de la linealidad</td>
<td align="left">3</td>
<td align="left"><span class="math inline">\(1.64\)</span></td>
<td align="left"><span class="math inline">\(0.55\)</span></td>
</tr>
<tr class="even">
<td align="left">Dentro de grupos</td>
<td align="left"><span class="math inline">\(14\)</span></td>
<td align="left"><span class="math inline">\(117.27\)</span></td>
<td align="left"><span class="math inline">\(7.82\)</span></td>
</tr>
<tr class="odd">
<td align="left">Total</td>
<td align="left"><span class="math inline">\(19\)</span></td>
<td align="left"><span class="math inline">\(6869.20\)</span></td>
<td align="left"></td>
</tr>
</tbody>
</table>
<p>El valor de <span class="math inline">\(F = \frac{0.55}{7.82} = 0.070 &lt; 1\)</span>. Por lo tanto no se rechaza
<span class="math inline">\(H_0\)</span>.</p>
<p>Luego podemos proceder y comprobar si la regresión es significativa como se
hizo para una regresión lineal simple sin replicas en la sección anterior.</p>
<p>En <em>R</em> es posible poner a prueba la linealidad de forma simple con una prueba
de anova. La formula general que se debe utilizar es:</p>
<pre class="sourceCode r"><code class="sourceCode r">variable_respuesta <span class="op">~</span><span class="st"> </span>variable_explicatoria <span class="op">+</span><span class="st"> </span><span class="kw">as.factor</span>(variable_explicatoria)</code></pre>
<p>Si no ponemos el segundo término a mano derecha, solo se hará una regresión
lineal. Por eso, se agrega la función <code>as.factor()</code> para que utilice la
segunda variable explicatoria como variable de agrupamiento y no como variable
continua como ya fue utilizada anteriomente. Por ejemplo, para los datos de
presión sistólica:</p>
<pre class="sourceCode r"><code class="sourceCode r"><span class="kw">summary</span>(<span class="kw">aov</span>(presion <span class="op">~</span><span class="st"> </span>edad <span class="op">+</span><span class="st"> </span><span class="kw">as.factor</span>(edad), <span class="dt">data =</span> presion_long))</code></pre>
<pre><code>##                 Df Sum Sq Mean Sq F value   Pr(&gt;F)    
## edad             1   6750    6750  863.45 1.13e-14 ***
## as.factor(edad)  3      2       1    0.07    0.975    
## Residuals       15    117       8                     
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<p>El orden de los factores <strong>altera el producto</strong>. No es lo mismo poner:</p>
<pre class="sourceCode r"><code class="sourceCode r">variable_respuesta <span class="op">~</span><span class="st">  </span><span class="kw">as.factor</span>(variable_explicatoria) <span class="op">+</span><span class="st"> </span>variable_explicatoria</code></pre>
<p>Comparase el resultado siguiente con el anterior</p>
<pre class="sourceCode r"><code class="sourceCode r"><span class="kw">summary</span>(<span class="kw">aov</span>(presion <span class="op">~</span><span class="st"> </span><span class="kw">as.factor</span>(edad) <span class="op">+</span><span class="st"> </span>edad, <span class="dt">data =</span> presion_long))</code></pre>
<pre><code>##                 Df Sum Sq Mean Sq F value   Pr(&gt;F)    
## as.factor(edad)  4   6752  1688.0   215.9 4.62e-13 ***
## Residuals       15    117     7.8                     
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<p>¡Y llegaremos a conclusiones totalmente opuestas!</p>
<p>Una vez que no rechazamos la hipotesis de que la población es linear podemos
comprobar que la regresion linear es significativa y estimar los parametros.</p>
<p>En el el ejemplo:</p>
<p><span class="math display">\[
b = \frac{\sum xy}{\sum x^2} = \frac{5180}{3975} = 1.3031447 \text{mm Hg/año}\\
a = \overline{Y} - b \overline{X} = 137.2- 1.3031447 52.5 = 68.7849057
\]</span>
En <em>R</em> es posible ajustar un modelo lineal con la función <code>lm()</code> que funciona
de forma similar a <code>aov()</code> (de hecho son lo mismo con cambios estéticos a
la forma de presentar los datos). Necesita una fórmula y la ubicación de los
datos.</p>
<p>El resultado puedo verse con la función <code>summary()</code> y puede verse abajo.</p>
<pre class="sourceCode r"><code class="sourceCode r"><span class="kw">summary</span>(<span class="kw">lm</span>(presion <span class="op">~</span><span class="st"> </span>edad, <span class="dt">data =</span> presion_long))</code></pre>
<pre><code>## 
## Call:
## lm(formula = presion ~ edad, data = presion_long)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -4.0050 -1.9186 -0.4421  2.0264  4.0893 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept) 68.78491    2.21607   31.04   &lt;2e-16 ***
## edad         1.30314    0.04077   31.97   &lt;2e-16 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 2.57 on 18 degrees of freedom
## Multiple R-squared:  0.9827, Adjusted R-squared:  0.9817 
## F-statistic:  1022 on 1 and 18 DF,  p-value: &lt; 2.2e-16</code></pre>
<pre class="sourceCode r"><code class="sourceCode r"><span class="kw">summary.aov</span>(<span class="kw">lm</span>(presion <span class="op">~</span><span class="st"> </span>edad, <span class="dt">data =</span> presion_long))</code></pre>
<pre><code>##             Df Sum Sq Mean Sq F value Pr(&gt;F)    
## edad         1   6750    6750    1022 &lt;2e-16 ***
## Residuals   18    119       7                   
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<p>Da casi toda la información necesaria.</p>
<ul>
<li><code>Call</code> da información de como fue ejecutado <code>lm()</code>.</li>
<li><code>Residuals</code> un breve resumen de los residuales, mínimo, primer cuartil,
mediana, tercer cuartila y máximo.</li>
<li><code>Coefficients</code> los coeficientes de los parámetros del modelo. <code>(Intercept)</code> es
la ordenada al origen y los siguientes coeficientes corresponden a la pendiente
de la variable nombrada. Indica el valor estimado, su error estándar, el valor
del estadístico <em>t</em> y la probabilidad de un valor mayor.</li>
<li>Abajo da también información del error estándar del residual. El r<sup>2</sup> múltiple
y ajustado. Y el estadístico F con sus grados de libertad y su valor de una
probabilidad mayor.</li>
</ul>
</div>
<div id="transformaciones-para-corregir-la-falta-de-linealidad" class="section level2">
<h2><span class="header-section-number">17.3</span> Transformaciones para corregir la falta de linealidad</h2>
<p>Muchas veces las relaciones entre <span class="math inline">\(X\)</span> e <span class="math inline">\(Y\)</span> no son lineales. Anteriormente,
vimos que se podía transformar <span class="math inline">\(Y\)</span> para cumplir los supuestos de normalidad y
homocedasticidad. Ahora veremos que también se puede transformar <span class="math inline">\(X\)</span> para
cumplir con la linealidad. En general, la transformación de <span class="math inline">\(X\)</span> no cambia
la distribución de <span class="math inline">\(Y\)</span> por lo que puede trasnformarse el primero con
impunidad.</p>
<p>Sin embargo, hay que tener cuidado con la transformaciones de <span class="math inline">\(Y\)</span>. No deben
hacerse en caso de que sí se cumplan los supuestos ya que se modificaría la
distribución de <span class="math inline">\(Y\)</span> y podrían dejar de cumplir estos supuestos.</p>
<table>
<thead>
<tr class="header">
<th align="right">X</th>
<th align="left">Y</th>
<th align="right">s2Y</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="right">5</td>
<td align="left">10.72, 11.22, 11.75, 12.31</td>
<td align="right">0.4684667</td>
</tr>
<tr class="even">
<td align="right">10</td>
<td align="left">14.13, 14.79, 15.49, 16.22</td>
<td align="right">0.8100917</td>
</tr>
<tr class="odd">
<td align="right">15</td>
<td align="left">18.61, 19.5, 20.4, 21.37</td>
<td align="right">1.4051333</td>
</tr>
<tr class="even">
<td align="right">20</td>
<td align="left">24.55, 25.7, 26.92, 28.18</td>
<td align="right">2.4452250</td>
</tr>
<tr class="odd">
<td align="right">25</td>
<td align="left">32.36, 33.88, 35.48, 37.15</td>
<td align="right">4.2525583</td>
</tr>
</tbody>
</table>
<table>
<thead>
<tr class="header">
<th align="right">X</th>
<th align="left">Y</th>
<th align="right">s2logY</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="right">5</td>
<td align="left">1.03019, 1.04999, 1.07004, 1.09026</td>
<td align="right">0.000668</td>
</tr>
<tr class="even">
<td align="right">10</td>
<td align="left">1.15014, 1.16997, 1.19005, 1.21005</td>
<td align="right">0.000665</td>
</tr>
<tr class="odd">
<td align="right">15</td>
<td align="left">1.26975, 1.29003, 1.30963, 1.3298</td>
<td align="right">0.000665</td>
</tr>
<tr class="even">
<td align="right">20</td>
<td align="left">1.39005, 1.40993, 1.43008, 1.44994</td>
<td align="right">0.000665</td>
</tr>
<tr class="odd">
<td align="right">25</td>
<td align="left">1.51001, 1.52994, 1.54998, 1.56996</td>
<td align="right">0.000666</td>
</tr>
</tbody>
</table>
<p><img src="regresion_files/figure-html/unnamed-chunk-10-1.png" width="672" /></p>
</div>
<div id="uso-de-los-residuales-para-comprobar-los-supuestos" class="section level2">
<h2><span class="header-section-number">17.4</span> Uso de los Residuales para Comprobar los Supuestos</h2>
<p>Incluso si no tenemos réplicas para cada <span class="math inline">\(X\)</span> es posible comprobar los supuestos
mediante el uso de gráficos de residuales. Una de las formas es graficando los
residuos vs los valores ajustados. Si hay homocedasticidad y la
regresión lineal es un buen modelo de ajuste a nuestros datos obtendremos
un gráfico de ajuste como el que se muestra en la Figura <a href="regresion.html#fig:residuales">17.3</a>a.
En este gráfico, los residuales muestran la misma varianza a lo largo de la
valores de <span class="math inline">\(X\)</span> y están distribuidos de igual manera alrededor del cero.</p>
<p>Si no se cumple el supuesto de homocedasticidad, es decir que hay
heterocedaticidad, el gráfico de los residuos se verá como en la Figura
<a href="regresion.html#fig:residuales">17.3</a>b. En este caso la variabilidad de los residuales aumenta
a medida que aumentan los valores predichos. También podría darse el caso
inverso, que la varianza disminuya a medida que aumente la media, pero es mucho
más raro. Si ocurre el caso de la Figura <a href="regresion.html#fig:residuales">17.3</a>c es probable
que falte una variable importante a nuestro modelo. Finalmente, si ocurre</p>
<div class="figure"><span id="fig:residuales"></span>
<img src="regresion_files/figure-html/residuales-1.png" alt="Gráficos de algunos de los posibles patrones que se pueden detectar al gráficar los residuales vs los valores ajustados." width="672" />
<p class="caption">
Figura 17.3: Gráficos de algunos de los posibles patrones que se pueden detectar al gráficar los residuales vs los valores ajustados.
</p>
</div>
</div>
<div id="regresiones-multiples" class="section level2">
<h2><span class="header-section-number">17.5</span> Regresiones Múltiples</h2>

</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="practico-de-pruebas-no-parametricas-para-muestras-relacionadas.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="ordenacion-en-espacios-reducidos.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/lunr.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"google": false,
"linkedin": false,
"weibo": false,
"instapper": false,
"vk": false,
"all": ["facebook", "google", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": "https://github.com/rstudio/bookdown-demo/edit/master/regresion.Rmd",
"text": "Edit"
},
"download": ["EACN.pdf", "EACN.epub"],
"toc": {
"collapse": "subsection"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://cdn.bootcss.com/mathjax/2.7.1/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:" && /^https?:/.test(src))
      src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
